### ISSUE TITLE
Negative Promt Timeout

### ISSUE THREAD

**Issue by Celuni** [safing/portmaster-ui#114]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**: I can set the prompt timeout to be a negative value.

**What you expected to happen**: Either capped at -1 or 0 to keep the prompt infinitely.

**How to reproduce it (as minimally and precisely as possible)**: Typing a negative value ex.: **-999** or using the UI to decrease the value.

**Anything else we need to know?**: I haven't looked in the source but you probably already verify a value to be positive but still it should be capped in UI too.

**Environment**: 

Portmaster Version: 0.6.5

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

**Comment by dhaavi** [comment]
Hey @Celuni, thanks for bringing this to our attention and sorry for the long delay in providing a response.

We actually did not have extended validation for excluding certain ranges 🙈. I fixed this in safing/portmaster#264.
