### ISSUE TITLE
[APP] Removed a check mark from the filters list and it comes back hours later

### ISSUE THREAD

**Issue by trekjunky** [safing/portmaster-ui#118]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:
I removed a check mark from the filters list and it comes back hours later
**What you expected to happen**:
The check mark to stay removed
**How to reproduce it (as minimally and precisely as possible)**:
wait 8 hours
**Anything else we need to know?**:
If I click the Round X, the check mark comes back immediately.
**Environment**:
OpenSuSE Tumbleweed
 Linux 64 bit
Portmaster Version: 
0.6.5
<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
  PortmasterVersion:0.6.5License:AGPLv3
Build Date:11.02.2021
Build Host:docker
Build Source:https://github.com/safing/portmaster
Build User:user
Build Options:main.go
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [ ] Windows 10
- [x] Linux
  - Please provide the output of `cat /etc/os-release`
NAME="openSUSE Tumbleweed"
# VERSION="20210217"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210217"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210217"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
 - Linux: `/var/lib/portmaster/logs` Core: eror log
 - ^ANJ{"Created":1613585592,"Modified":1613585592,"Expires":1616177592,"Deleted":0}S
executing core/portmaster-core version 0.6.5 on linux amd64
 
Core cat last log | grep facebook gave me this at the tail:
210218 23:24:20.432 connection:564 ▶ INFO 936 filter: connection trekjunky:/usr/lib64/opera/opera:30131 to edge-chat.facebook.com. (2a03:2880:f003:c07:face:b00c:0:2) accepted: default permit
210219 19:58:24.220 nameserver:166 ▶ INFO 677 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 19:58:24.220 nameserver:166 ▶ INFO 678 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 19:58:31.212 nameserver:166 ▶ INFO 738 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 19:58:31.216 nameserver:166 ▶ INFO 740 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 19:58:46.644 nameserver:166 ▶ INFO 989 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 19:58:46.648 nameserver:166 ▶ INFO 991 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:02.143 nameserver:166 ▶ INFO 165 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:02.147 nameserver:166 ▶ INFO 168 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:17.750 nameserver:166 ▶ INFO 341 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:17.755 nameserver:166 ▶ INFO 343 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:33.592 nameserver:166 ▶ INFO 534 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:33.596 nameserver:166 ▶ INFO 536 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:34.979 nameserver:166 ▶ INFO 610 nameserver: request for connect.facebook.net.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:34.979 nameserver:166 ▶ INFO 612 nameserver: request for connect.facebook.net.A from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:48.884 nameserver:166 ▶ INFO 664 nameserver: request for connect.facebook.net.A from nscd:/usr/sbin/nscd:892 blocked
210219 19:59:48.892 nameserver:166 ▶ INFO 667 nameserver: request for connect.facebook.net.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:00:04.388 nameserver:166 ▶ INFO 831 nameserver: request for connect.facebook.net.A from nscd:/usr/sbin/nscd:892 blocked
210219 20:00:04.392 nameserver:166 ▶ INFO 833 nameserver: request for connect.facebook.net.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:00:20.144 nameserver:166 ▶ INFO 031 nameserver: request for connect.facebook.net.A from nscd:/usr/sbin/nscd:892 blocked
210219 20:00:20.148 nameserver:166 ▶ INFO 034 nameserver: request for connect.facebook.net.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:00:35.523 nameserver:166 ▶ INFO 183 nameserver: request for connect.facebook.net.A from nscd:/usr/sbin/nscd:892 blocked
210219 20:00:35.527 nameserver:166 ▶ INFO 188 nameserver: request for connect.facebook.net.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:00:51.352 nameserver:166 ▶ INFO 389 nameserver: request for connect.facebook.net.A from nscd:/usr/sbin/nscd:892 blocked
210219 20:00:51.356 nameserver:166 ▶ INFO 391 nameserver: request for connect.facebook.net.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:03.217 nameserver:166 ▶ INFO 464 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:03.217 nameserver:166 ▶ INFO 465 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:10.521 nameserver:166 ▶ INFO 522 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:10.525 nameserver:166 ▶ INFO 524 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:25.717 nameserver:166 ▶ INFO 577 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:25.722 nameserver:166 ▶ INFO 579 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:40.976 nameserver:166 ▶ INFO 643 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:40.982 nameserver:166 ▶ INFO 645 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:56.169 nameserver:166 ▶ INFO 700 nameserver: request for www.facebook.com.A from nscd:/usr/sbin/nscd:892 blocked
210219 20:04:56.173 nameserver:166 ▶ INFO 702 nameserver: request for www.facebook.com.AAAA from nscd:/usr/sbin/nscd:892 blocked
210219 20:05:11.518 nameserver:239 ▶ INFO 789 nameserver: returning accepted response (NOERROR) for www.facebook.com.A to nscd:/usr/sbin/nscd:892
210219 20:05:11.547 nameserver:239 ▶ INFO 791 nameserver: returning accepted response (NOERROR) for www.facebook.com.AAAA to nscd:/usr/sbin/nscd:892

- Windows: `%PROGRAMDATA%\Portmaster\ļogs`

**Comment by trekjunky** [comment]
I think it is fixed. I locked the other people in the house out of my computer and it stayed overnight.

**Comment by trekjunky** [comment]
Nope, I think there was an update that reset the selected filters. Is there any way to remember what was deselected before an update?

**Comment by ppacher** [comment]
Hi @trekjunky,

thanks for reporting that issue. An update itself should not reset any user settings so there's nothing special you need to do.  This is likely the same issue that has been reported in safing/portmaster#260. We are currently investigating that and will come back to you once we know what's causing that reset.

**Comment by dhaavi** [comment]
Both @ppacher and I had another look at this issue and we weren't able to reproduce this issue. 😕 This means that we'll need more details from you in order to know where to look and how to try to reproduce. There seems to be a special condition for this to occur.

We released [v0.6.6](https://github.com/safing/portmaster/releases/tag/v0.6.6) today, please update and try to reproduce with the new version.

**Comment by northys** [comment]
@dhaavi for some reason firefox app overrides vanish more often than the one changed for dig (I even forgot I changed something for dig but very often change firefox settings because translate.google.com got broken because of blocking of fonts.google.com). couldn't it just fanish from bolt db?

**Comment by dhaavi** [comment]
That is kind of problem I'm having here. There currently is no at all code that deletes app setting profiles from the database. So I'm guessing that an older version is overwriting the newer one at some point. But! Nothing changes app setting profiles except:
- (1) The Portmaster itself on initial creation.
- (2) When processing prompt responses.
- (3) Changing it through the UI.

So, (1) should not be the case and (2) and (3) are user actions (Did these happen?). That's where I'm at now.

Here are a couple questions that could help me make sense of this:
- Does just the filter list setting disappear or all of the settings?
- After you make a change, please copy the following information and check if these change when a setting disappeared:
  - `ID` (You'll need to switch to the Developer UI)
  - `Created`
  - `Last Used`

**Comment by dhaavi** [comment]
We are opening a possibly related investigation about weird app settings behavior in https://github.com/safing/portmaster/issues/391, as we continue to receive similar reports every now and then.
