### ISSUE TITLE
monochrome Destop-Icons for KDE-Tray

### ISSUE THREAD

**Issue by Watson15683** [safing/portmaster-ui#120]
**What would you like to be added**:
I would like a monochrome Destop-Icon-Option for the KDE-Notifications-Tray. Like with the Nextcloud-Luncher.
And the Icon is quite Big. A litte bit smaler would be nice.

**Why is this needed**:
All all my other icons are monochrom, and the big Icon with the green Dot seems a litte odd. 
![grafik](https://user-images.githubusercontent.com/79628154/110295552-862eec00-7ff1-11eb-83d1-66e738dc9de3.png)

### Additional Info
OS: Linux Mint
Portmaster Version: 0.6.5

**Comment by dhaavi** [comment]
Hey @Watson15683,

thanks for reporting this! We are currently gathering feedback on Desktop Environment compatibility and will tackle these issues together in the future.

Could you tell we which version of KDE you are currently running?

**Comment by dhaavi** [comment]
Thanks!

I'll keep this issue open and we'll get back to you when we start tackling the Notifier issues on Linux.
