### ISSUE TITLE
Load app icons on Linux and/or give option to add manually

### ISSUE THREAD

**Issue by ItsDrike** [safing/portmaster-ui#121]
### What happened
The UI of PortMaster doesn't detect any application icons and uses only the initial letters as icons. This is probably not the case on Windows-based systems (assumption from readme screenshots, where icons are clearly working).

![image](https://user-images.githubusercontent.com/20902250/110398906-1f531680-8075-11eb-877e-8c9b9448b669.png)

### What you expected to happen
There should be support for Linux icons too, icons should be autodetected and displayed, rather than using the initial letters only, which makes it hard to orientate quickly in the UI.

I can understand if there would be some technical difficulties with implementing this, and if that is the case, there should at least be a way to add them manually, in the application edit men, by simply selecting the icon in the file manager.

### How to reproduce it
1. Install portmaster on arch Linux (likely affects other distributions too), 
2. Open UI using `portmaster-start app --data=/var/lib/portmaster` command
3. Observe icons only using the first letters of applications, instead of normal icons associated with the apps.

### Environment
**OS:** Arch Linux (5.10.16.arch1-1, architecture: x86_64)
**Desktop Environment:** KDE Plasma (5.21.0-2)
**Portmaster version:** `0.6.5` (built from PKGFILE of https://github.com/safing/portmaster-packaging/commit/289cf3eb790fbe7bdd7c2d029504294acf3b5350 )

___

<details>
<summary>Further portmaster version details</summary>

```
Portmaster
version 0.6.5

commit tags/v0.6.5-0-g6c0df1155e5bc19e8b749875ef984c34eeb8b315
built with go1.15.8 (gc) linux/amd64
  using options main.go
  by user@docker
  on 11.02.2021

Licensed under the AGPLv3 license.
The source code is available here: https://github.com/safing/portmaster
```

</details>

<details>
<summary>Unexpected Logs</summary>

```
210309 00:30:08.698 ds_by_user:053 ▶ WARN 185 proc: could not stat /proc/250079: stat /proc/250079: no such file or directory
210309 00:33:52.808 CURRENT TIME
```

</details>

**Comment by ppacher** [comment]
Hi @ItsDrike,
thanks for trying out and taking the time to report this. This is actually known behavior as we have not yet implemented support for the required freedesktop.org specifications (desktop-files and icon-theme). Though, this is definitely on our TODO list!

Thanks for the suggestion of manually adding those icons. We will discuss this with the team as it's a lot easier to implement in the short term.
