### ISSUE TITLE
portmaster icon looks blurry

### ISSUE THREAD

**Issue by Taza53** [safing/portmaster-ui#126]
As seen in the picture the bottom part of the icon is somewhat off
![image](https://user-images.githubusercontent.com/34032665/111500292-1f71a700-8744-11eb-8033-12eb7a89292c.png)

**Comment by dhaavi** [comment]
Hey @Taza53, thanks for bringing this to our attention. Sorry, we somehow missed this issue the last weeks.

I am adding this to our UI Tuning milestone, as we will be looking into a lots of such issues together in the future.
