### ISSUE TITLE
Improve app information section in the monitor view

### ISSUE THREAD

**Issue by Taza53** [safing/portmaster-ui#129]
![image](https://user-images.githubusercontent.com/34032665/111485017-8c7e4000-8736-11eb-83d9-b8470782077a.png)
increase spacing.
if click to copy path could be added it would be helpful.

_Originally posted by @Taza53 in https://github.com/safing/portmaster/issues/151#issuecomment-801132684_

**Comment by dhaavi** [comment]
Thanks!

**Comment by dhaavi** [comment]
Hey @Taza53, the spacing was fixed a while ago.
Also, a click on the path or other data will select the full value so you can quickly copy it.

Please report back if everything works as expected for you.

**Comment by Taza53** [comment]
yes everything work well
