### ISSUE TITLE
Allow collapsing of left bar

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#138]
**What would you like to add or change?**:

Please allow collapsing of the left bar.

It would be awesome if the taskbar collapses automatically on 720p and lower resolution.

**Why do you and others need this?**:

On low resolutions (or when one has portmaster in a smaller window than full screen) the portmaster is barely usable because most of the text gets hidden or badly wrapped. This is IMHO a really fast fix to make it usable on 720p or when windowed.

**Comment by dhaavi** [comment]
Yes! We already have something like this in mind.

While just hiding it the sidedash (thats what we call the column with the shield) is a really fast fix, it should stay accessible somehow and that makes it a bit more difficult.

Anyway, this is planned and it's nice to see support for this idea from the community!

Internal note: tracked by CC#1627.

**Comment by player2joinedthegame** [comment]
+1 to above suggestion either by making each column draggable/resizable or by creating a minimized view over the main overview.

anyway we can help? do you welcome if we submit a pull request to amend this?? best regards & thank you for such great work already!

**Comment by ppacher** [comment]
This is now supported in the new side-dash :rocket:. It's already released to the Beta release channel and will enter Stable soon.
Hence, I'm closing this one
