### ISSUE TITLE
search bar ui change in network monitor

### ISSUE THREAD

**Issue by Taza53** [safing/portmaster-ui#144]
**What would you like to add or change?**:
![image](https://user-images.githubusercontent.com/34032665/117273313-4ef78280-ae5c-11eb-9177-50125b5747f7.png)
when you press the search icon you can not start typing you have to press again to start typing. The enhancement is to just make it so when clicked on the search icon it allows me to search rather than me having to press the search bar again,

**Why do you and others need this?**:
just more intuitive

**Comment by dhaavi** [comment]
Hey @Taza53, nice find! Thanks!

We're are going to look into this.

Internal note: tracked by CC#1925.
