### ISSUE TITLE
Blocking an IP/Domain via Button has no immediate feedback, which is confusing

### ISSUE THREAD

**Issue by darkskyfullofstars** [safing/portmaster-ui#150]
**What would you like to add or change?**:

I would like it so when i go to click block ip it changes to ip blocked and keeps it blocked and able to see that its blocked.

**Why do you and others need this?**:

everyone would love to be able to see if an ip is blocked when they click block ip because right now it does nothing to show that its blocked or allowed.

**Comment by davegson** [comment]
could you elaborate a bit more? Are you mainly concerned of the visual representation of what is happening?

When you see a request you dislike and then block it, it will block all following requests, but cannot revert the connection that already happened. A notification should pop up at the left side in the app to indicate the rule was added to one of the rules list, either the [Outgoing Rules](https://docs.safing.io/portmaster/settings#filter/endpoints) or the [Incoming Rules](https://docs.safing.io/portmaster/settings#filter/serviceEndpoints).

I do understand it might not be presented in a way which is easy to understand, do you maybe have a suggestion how we could make it better?
