### ISSUE TITLE
Overview-panel for all rules

### ISSUE THREAD

**Issue by R1123345** [safing/portmaster-ui#152]
**What would you like to add or change?**:
What is great about portmaster is that it offers a level of control and information in a way no other firewall does. What is missing, is a place you can see all the default rules and exceptions to it in one glance. 

**Why do you and others need this?**:
It is currently unclear where you can find relevant information

**Comment by LukeSeers** [comment]
Hey mate. Thanks for the feedback. Can you give me a bit more detail in what your wanting please? I think I understand, but I'm a bit unsure. I want to make sure, that I fully understand your suggestion thanks :)
