### ISSUE TITLE
Tray notification fills the entire screen

### ISSUE THREAD

**Issue by ppacher** [safing/portmaster-ui#155]
> Also I want to add further feedback on the error above regarding update check. Right-clicking the portmaster tray icon will fill the entire screen with the error message (minor QoL stuff). I apologize if I'm clogging the thread with this.

![Screenshot from 2021-07-07 22-05-33](https://user-images.githubusercontent.com/79779282/124778562-a22ca500-df73-11eb-9685-3040c6a09f4d.png)

_Originally posted by @zer0exia in https://github.com/safing/portmaster/issues/292#issuecomment-875662788_

**Comment by SirRFI** [comment]
Same on Windows when left or right-clicking the tray icon

![image](https://user-images.githubusercontent.com/32642697/145650742-5604b581-218f-409a-bcc1-99a7e97cc50f.png)

**Comment by dhaavi** [comment]
Thanks for the additional report - this will be fixed in the next tray notifier update.
