### ISSUE TITLE
Problems starting the notifier

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster-ui#167]
Notifier does not work anymore, it worked the first few times just fine. I reinstalled a few times and now no pop ups are showed anymore and the icon tray is no longer working. I used the same dependencies as before when building so I'm not sure how this happens. ( all install files, configs etc are deleted from me manual after reinstall)

which dependencies are used for building, which os your building on?

i had to use the aur media-control-indicator-git because the  libappindicator is not in the offical repository

normal start does not work at all

i cant run the notifier as non sudo user because it cant communicate with the service

`Error: failed to exec lock: open /var/lib/portmaster/exec/notifier-lock.pid: permission denied
`

sudo /var/lib/portmaster/portmaster-start notifier --data=/var/lib/portmaster
works but 

> 911 20:28:44.490 tify_linux:132 ▶ WARN 014 notify: failed to show notification filter:prompt-9f3c32aa-2beb-4fbf-8eff-8af681e1314e-duckduckgo.com.
> 210911 20:28:46.008 tify_linux:132 ▶ WARN 016 notify: failed to show notification filter:prompt-9f3c32aa-2beb-4fbf-8eff-8af681e1314e-github.com.
>

also i can see than the tray icon but when i click "Open App" nothing happens
maybe because i opened it seperate from the main process. but closing the notifier works.

this is also weird because on the arch installer you add 2 different applications to be launched by the os (which is confusing and does not work properly)

portmaster.desktop <--- does not start the notifier on exit
portmaster_notifier.desktop <-- this is by default not run by with the privileges, maybe you catch this and execute this with the portmaster running as root, but currently its useless and kills itself after a short time

os: manjaro

this issue exists from core 0.18 - 0.22 (which i have tested) and the notifier is also useless , but i can confirm it once worked and that very well in terms of pop ups  but the icon tray working i cant confirm. but i remember 3 months ago or so it worked.

any suggestions which may help, let me know, will try to fix it

_Originally posted by @kittkatter in https://github.com/safing/portmaster-ui/issues/166#issuecomment-917507204_

**Comment by kittkatter** [comment]
haven't seen this issue on ubuntu. i will try to fix this. weirdly i got it working but i don't know yet what caused the problem.

**Comment by dhaavi** [comment]
Thanks @kittkatter for raising this issue. This seems to be same as https://github.com/safing/portmaster-ui/issues/168. Here is a possible solution:

From what I understand the notifier seems to have been started with root/admin privileges and did not correctly shut down, leaving a lock with root/admin ownership behind.
This prevents normal users from starting the notifier.
If you just remove the lock file, everything should work again.

Lock file location:
- Windows: `C:\ProgramData\Safing\Portmaster\exec\notifier-lock.pid`
- Linux `/var/lib/portmaster/exec/notifier-lock.pid`

This is mainly based on the information from @kittkatter, so while I think this is the same as you are experiencing @Rittmeister39, it may in fact be not. Please test the solution and report back.

**Comment by kittkatter** [comment]
once i chmod 777 the file, it worked.

**Comment by ppacher** [comment]
Hi @kittkatter,
glat do here this is now resolved and works for you.

I'll keep the issue open until we have a dedicated fix for that. I guess the notifier could refuse to start as root. Or at least, if it was ever started as a non-root user.

I'll discuss this with @dhaavi

**Comment by dhaavi** [comment]
We've haven't seen this issue for a while now, so I guess we can close this. Please reopen or create a new issue if you experience this issue.
