### ISSUE TITLE
Add a Light Theme

### ISSUE THREAD

**Issue by subnut** [safing/portmaster-ui#169]
**What would you like to add or change?**:
Please add a light theme.

**Why do you and others need this?**:
My whole system is in light mode. This makes looking at this app very hard. Please add a light theme.

**Comment by LukeSeers** [comment]
Hey @subnut

You will be delighted to hear that this is already planned for the future. It's not shown in https://safing.io/backlog/#portmaster since it's not high on our priority list, but this will be added for sure.

**Comment by davegson** [comment]
👍 +1 came in via mail

**Comment by davegson** [comment]
another 👍 +1 [from MalwareTips](https://malwaretips.com/threads/portmaster-firewall-alpha-stage.108383/post-964036)

**Comment by northys** [comment]
one completely worthless post by @northys

![128978663327520110725-22047-1x5td48](https://user-images.githubusercontent.com/2878126/159382262-2ca6accd-c876-49d3-8e40-0347150ac9ae.png)

**Comment by northys** [comment]
@dhaavi dont be so serious :D thats why i said "completely worthless post". i love the dark theme. i have dark mode everywhere.

**Comment by mhosem2nd** [comment]
+1 here 👍
