### ISSUE TITLE
24-hour format

### ISSUE THREAD

**Issue by ner00** [safing/portmaster-ui#183]
**What would you like to add or change?**:
Allow choosing to display time as 24-hour format instead of only 12-hour format (AM/PM).

**Why do you and others need this?**:
Most countries use 24-hours format, this could be of interest to a good chunk of the user-base.

**Comment by dhaavi** [comment]
I'm with you - will bring this up with the team.

**Comment by itsnotsaved** [comment]
Sorry, please offer both options to customize

**Comment by dhaavi** [comment]
Thanks for your input. We have not yet moved forward with this, as there were more pressing matters.

Internally tracking this at CC#2167.

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
