### ISSUE TITLE
Make double-click on Notifier (systray-icon) open/focus Portmaster

### ISSUE THREAD

**Issue by ner00** [safing/portmaster-ui#184]
**What would you like to add or change?**:
At least in Windows environment, double-clicking a systray icon usually opens/maximizes/focuses the main window. I frequently find myself double-clicking the tray icon to open the app but all it does is open the context menu. Could even allow customization of single-click and not only double-click.

**Why do you and others need this?**:
While Windows functionality is pretty popular, it is by no means the standard by which things should be molded. That being said, there are also popular Linux desktop interfaces that follow the same logic, so allowing to customize the interaction with the systray icon would be nice for any OS.

**Comment by dhaavi** [comment]
Hey @ner00, thanks for the suggestion!

I'm not too much of a Windows user, but I see your point. I'm not sure if we can easily do this right now, ie. if the library we use supports this. Will have a look when we update the notifier the next time.
Adding to backlog to investigate.

**Comment by Kiefy** [comment]
There is another issue https://github.com/safing/portmaster-ui/issues/338 that is very similar, with some good input.
