### ISSUE TITLE
Engine Compatibility Issues

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster-ui#19]
There are mutliple issues that appear on certain platforms, that are not present in regular browsers used in development:

Linux:
- Settings: Dropdowns won't show, but are still clickable.
- Profile Manager: Module freezes when clicking on a security level button

**Comment by ppacher** [comment]
Can we close it? This is pretty old and likely obsolete.

**Comment by ppacher** [comment]
Sorry, wrong button

**Comment by dhaavi** [comment]
Yes, I think this can be closed. Currently, everything seems to be fine.
