### ISSUE TITLE
Save notification confirmation

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#191]
**What would you like to add or change?**:

I would love to see a popup notification saying "settings have been saved". Similar to one that is fired when I try to change settings to unsupported state. I always tend to search for the save button (because I don't use the UI much) after I dig into some settings. That notification would immediately tell me that my changes are being used.

**Why do you and others need this?**:

It's simple and nice change that improves UX a lot.

**Comment by dhaavi** [comment]
Yup. We have talked about that already internally, but somehow it hasn't made it yet.

Thanks for the reminder.
Now tracking this internally at CC#2197.

**Comment by dhaavi** [comment]
This is coming. Already marking.

**Comment by northys** [comment]
@dhaavi that means I should test it? Portmaster says there are no updates and I don't see any popup when making changes.

```
Portmaster
version 0.7.21

commit tags/v0.7.21-0-ge1093d1da0aac04304e1ef0dc8742ac2a47feb10
built with go1.15.8 (gc) linux/amd64
  using options main.go
  by user@docker
  on 31.01.2022

Licensed under the AGPLv3 license.
The source code is available here: https://github.com/safing/portmaster
```

**Comment by dhaavi** [comment]
Sorry, no. I was too fast.
Coming to beta channel on monday.

**Comment by northys** [comment]
works for me
