### ISSUE TITLE
Disallow asterisk for IPs

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#192]
**What would you like to add or change?**:

When I tried to enable my local network for VLC to play DLNA content the portmaster happily saved allow rule `192.168.1.*` but it didn't work at all. Later I discovered in help dropdown that I should use CIDR notation to allow a subnet which makes sence but it's not BFU resistant :D

**Why do you and others need this?**:

I think this is a bug actually. Or better call it an unexpected edge case. I think asterisk should not be allowed for IPs only for hostnames / domains. Maybe portmaster could be so brilliant to change `192.168.1.*` to `192.168.1.1/24` but I don't like when an app saves something else. A simple yellow warning notification saying "use CIDR notation to allow/deny a subnet" would be just enough =)

**Comment by dhaavi** [comment]
I think it took `192.168.1.*` as a domain with a trailing wildcard.
And number only domains seem to be perfectly valid for at least some TLDs.

Hm. Not sure how to go about this.
I agree that it *feels* like entering a network, while being a domain. This is a problem.

**Comment by dhaavi** [comment]
Had a talk with @ppacher about this. We will apply a fix.

**Comment by northys** [comment]
@dhaavi what did you came up with? are you for magic asterisk to cidr translation or will it rather throw a warning or something like that?

**Comment by dhaavi** [comment]
We will just simply deny formats that could be misunderstood.
Ie. `192.168.1.*` will be regarded as invalid in the future.
While this might be a valid subdomain, it is _highly_ unlikely someone would ever want to enter that.
