### ISSUE TITLE
Connection History: persistent show settings

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#194]
**What would you like to add or change?**:

I would love if portmaster could remember (globally) that I have changed show settings between `Connections` and `by Domain`.

**Why do you and others need this?**:

I don't like the new grouped connections by domain you introduced few months ago and **it feels like I have to change it to my favorite old view again and again**.

**Comment by dhaavi** [comment]
At least in the current version released today this seems to work for me - can you check again?

**Comment by northys** [comment]
It works, but it's per app so that's the reason why it feels like I have to switch to the other one all the time. For me it's not must have but I would prefer it to be configurable globally for all apps at once. Now the default is **by Domain**.

It's up to you guys to decide whats best. cc @davegson

**Comment by northys** [comment]
No, It looks like it's global for all apps already... so I don't know why I had to change it again today...

**Comment by northys** [comment]
So it works globally but it is not persisted. On dashboard reopen it switches back to by Domain. I can live with that so it's up to @davegson if he wants to include persisting of this option in the future. Otherwise you can close this ticket.
