### ISSUE TITLE
No Sandbox needed ... (Why did you use electron? Jeez)

### ISSUE THREAD

**Issue by ata-star** [safing/portmaster-ui#196]
https://github.com/electron/electron/issues/18265

i am very sick of it ... The classic Elecron Nvidia Bug

[4294:0106/124909.635355:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

**Comment by davegson** [comment]
I understand you are frustrated, but it is neither helpful nor respectful to just vent your frustration towards us. You are welcome to participate within the terms of our [Code of Conduct](https://docs.safing.io/community/code-of-conduct)

On a technical matter, we know about the drawbacks of electron and [plan to switch at some point](https://docs.safing.io/portmaster/architecture/user-interface#faq). In the meantime, I would recommend [opensnitch](https://github.com/evilsocket/opensnitch) as an alternative.
