### ISSUE TITLE
Won't close when never show again is selected

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#198]
**What happened**:

There is new prompt when closing UI saying that closing UI won't stop portmaster. Also, there is a checkbox "Never show again" - when this checkbox is checked portmaster UI won't close after I click on close button in the prompt. Unchecking the box fixes this and portmaster UI closes.

**What did you expect to happen?**:

Portmaster UI closes even when "Never show again" checkbox is checked.

**How did you reproduce it?**:

Alt+F4, check "never show again" checkbox and click close button in the prompt. Portmaster won't close.

https://user-images.githubusercontent.com/2878126/150244568-f50dc411-a26d-4e32-b27d-efadd56fd8e1.mp4

**Comment by ppacher** [comment]
Hi @northys,
thanks for reporting! Unfortunately I failed to reproduce this issue.
Can you press F12 to open the developer tools and check if there are any error logs in the `Console` tab? If yes, it would be awesome if you could post them here.

**Comment by northys** [comment]
Hi, @ppacher, I wanted to debug it using F12. Unfortunally the debug toolbar did not show on F12 key press at all. I thought you disabled it. Maybe something under the hood was broken.

I can't replicate it right now but I recall I tried it multiple times back then. It seems like reboot or some update fixed it. Closing...
