### ISSUE TITLE
System DNS Client blocks DNS requests when it should not

### ISSUE THREAD

**Issue by working-name** [safing/portmaster-ui#203]
**What would you like to add or change?**:

Would it be reasonable to display blocked queries under the particular application given a match from a list? I don't know if that would overflow the UI with a never-ending list. If that's not a good user experience, then maybe with a debug switch, disabled by default?

**Why do you and others need this?**:

I was trying to figure out why my browsers were no longer resolving marchex.io and there was no feasible way to do that in the UI, I had to look at the logs where it finally stated `blocked: marchex.io. in activated lists OISD` (overzealous blacklist if you ask me). That process would have been a lot more obvious if there was some kind of notification in the UI I could watch right after making my request from the browser.

Some extra background:

Although I'm starting chrome with `--disable-async-dns` it still couldn't care less what the user wants. Which is 100% google, so no wonder there.

Of course the issue is compounded on windows specifically where chrome.exe tries its mommy's dns endpoints, then the system, and ultimately it hands off the request to svchost.exe. Therefore to "whitelist" the domain you have to add an allow rule to both chrome.exe and svchost.exe.

**Comment by dhaavi** [comment]
Hey @working-name,

We already have a overview for network monitor planned, where you can easily search all connections. This will come in the near to mid-term future.

Until then, to usual way to go about this, is:
- Open the UI.
- Select the browser / affected application in the network monitor.
- Using the filter button on the right, select "Blocked" to only show blocked connections.
- Click on one of the "Allow Domain" buttons on the blocked connection.

The Portmaster detects the instance of svchost.exe that does the resolving and uses the "System DNS Client" settings for it. Adding an exception for a domain to that profile is not necessary, as it is handled specially - see the description in the "System DNS Client" settings.

**Comment by working-name** [comment]
[Running 0.7.20 BETA right now]

Awesome, that sounds great! I recorded the current behavior which may be an unintended regression or some weird thing going on with windows 11 only - it seems to not attribute the requests to the app making the request, but only to svchost / system dns client. 

Also, the log doesn't seem to mention `blocked: marchex.com ... something list` anymore, I think that may only be mentioned once and then upon further requests to resolve the same domain, portmaster simply returns the cached response? Makes it a tad bit hard to figure out why it's blocked, but again, a non-issue overall given that you're already building something awesome.

Thank you!

https://user-images.githubusercontent.com/16505052/151394373-cab76468-defd-43d4-aa90-0d645b2c2084.mp4

**Comment by dhaavi** [comment]
Have you changed the settings of the System DNS Client?
Normally, it should not block domains directly, but resolve them and then block the connection when the Portmaster knows which app is actually behind the request.

**Comment by working-name** [comment]
I did change the settings, and then reset them to defaults after reading your comment. The DNS requests still get blocked at the level of `System DNS Client` rather than the source app, because `System DNS Client` also inherits global block list settings.

For example, if I wanted to allow access to badsite.com, right now I have 2 choices as far as I can see:

- override the global active lists for `System DNS Client` and disable all of them to allow all DNS queries, and then wait for the block lists to take effect in the app which requested that domain (untested)
- simply add rules to `System DNS Client` to allow the specific domain I'm interested in. 

Am I misunderstanding how things work? (again :grin:)

**Comment by working-name** [comment]
I deleted the profile for `System DNS Client` but it's still prompting for allow/deny, and it applies global settings filter lists from its entries in the `Blocked` filter of Connection History.
![still-prompting](https://user-images.githubusercontent.com/16505052/153925334-1bd47238-e56b-47d7-a3b4-be29e3f0b439.jpg)
![image](https://user-images.githubusercontent.com/16505052/153925338-e6eda63c-fd9e-4bfa-89be-8714ff0b7957.png)

**Comment by dhaavi** [comment]
> I deleted the profile for `System DNS Client` but it's still prompting for allow/deny, and it applies global settings filter lists from its entries in the `Blocked` filter of Connection History.

The System DNS Client profile should not be empty, but return to the defaults.
Reproduced.
Fix on the way in https://github.com/safing/portmaster/pull/533.

> By the way, since I've highjacked the thread with something different than the title suggests, and I'm okay with the Connection History filter workaround for now, maybe we can close this or rename/move the issue to reflect a problem in core rather than UI. grin Sorry!

No problem. Good point, I've updated the issue title and tags to reflect the contents.

**Comment by dhaavi** [comment]
Fix is now released in v0.8.2, available on the [Beta Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel).

**Comment by working-name** [comment]
This seems to be good now, I removed System DNS Client's profile again but it somehow retained some of the settings, but pressing the [`x`] in the right section returns it to normal. I can see now that it sets itself as `Allow` for the default network action and no filter lists enabled. Now the requesting app lists these connections and if they're blocked.

I don't know if the new UI for the `App Page` is part of the cool stuff coming, but I'm loving it so far. Also, thank you so much for making the rule buttons larger, much more comfortable to click them now (28" 4k screen, 125% scaling, windows 11). 

Amazing job, as usual. 

Thank you!
