### ISSUE TITLE
Tray Icon Light/Dark

### ISSUE THREAD

**Issue by LukeSeers** [safing/portmaster-ui#205]
**What would you like to add or change?**:
To easily toggle a light/dark colour for the postmaster tray icon.

**Why do you and others need this?**:
Some nice chap requested a custom Portmaster tray icon for a theme pack: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2978 with the reason:

> the icon is white, thats why you can not see it that good..

Depending what OS your running there can be many different colour styles for the taskbar, thus making it currently hard to see if they have a light taskbar. Being able to easily toggle a dark version of the tray icon would help.

**Comment by dhaavi** [comment]
I think I've already looked into this once and it wasn't easy to determine if the system was currently in light or dark mode.

But I think it's a good idea!
Tracking this internally at CC#1632.
