### ISSUE TITLE
Blue Dots Not Updating While Changing Settings

### ISSUE THREAD

**Issue by davegson** [safing/portmaster-ui#206]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/portmaster-ui/issues?q=is%3Aissue+label%3Abug)

**What happened**:
the blue dots in the settings nav tree, indicating one has diverged from the default settings do not update _while changing_ settings but only load when _opening_ the settings.

![Screen Shot 2022-02-16 at 2 13 10 PM](https://user-images.githubusercontent.com/3080765/154272562-53f1fe3c-cf5b-4a3b-937c-1ed2a34e5e50.png)

the blue line of the setting gets added, but not the dot in the nav tree

**What did you expect to happen?**:
eg: when I have the defaults in a category and I change one of its settings, the blue dot should appear

**How did you reproduce it?**:
1. go to a settings group where you have the defaults
2. change a setting
3. no blue dot will appear until setting are re-visited

same goes the other way around:

1. go to a settings group which already has a blue dot
2. reset all un-default settings to the default
3. blue dot will stay until settings are re-visited

**Debug Information**:

PM version 0.8.2

**Comment by ppacher** [comment]
Should be fixed once  #209 is merged.
