### ISSUE TITLE
Add tooltip to blue dots indicating settings change

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#208]
**What would you like to add or change?**:

It would be nice if the blue dot on the right had a tooltip explaining what does it means.

**Why do you and others need this?**:

It took me a while to realize what it is trying to tell me and why it is not next to each item. At the first it looked like a list to me.

**Comment by LukeSeers** [comment]
It's funny you say that, because we're already working on solving that problem https://github.com/safing/portmaster-ui/pull/207 :)

**Comment by northys** [comment]
I don't think it changed. There is no tooltip.

**Comment by dhaavi** [comment]
Hm. Maybe you meant different blue dots?

Do you mean the ones on the left in the menu or the ones to the right of a changed setting?

**Comment by northys** [comment]
Lol I said right and I think it is on the right. Yeah I meant the one in the menu. They are so tiny and small that the tooltip wouldnt be possible to trigger on mouse over... I'm closing this as it doesn't make sence for me.

I would call it a confusion after big redesign...
