### ISSUE TITLE
Allow *.domain button in connection history dropdown

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#211]
**What would you like to add or change?**:

I would love a quick action to add domain including all subdomains because most of the time I just have to enable multiple domains to get site working and most advanced site have something like `static.domain`, `api.domain` and so on and it makes rule list messy when you allow multiple domains every day.

I mean this dropdown:

![Screenshot from 2022-03-17 22-57-55](https://user-images.githubusercontent.com/2878126/158901425-436edfe2-452f-47c0-8003-3ad6b4526f51.png)

**Why do you and others need this?**:

It helps to keep rule list clean without having to enable domain with subdomains manually which is time consuming.

My usecase: I open example.com which is blocked so I allow it and get blocked www.example.com and after login a see error because api.example.com is blocked.

**Comment by northys** [comment]
There is a little privacy concern about this behavior because user can accidentally allow `trackingshit.domain` but I suppose those would be blocked by adblock's rule which matches script path/name rather than domain.

**Comment by northys** [comment]
Also, I would enable this option only for `2lvldomain.tld` and `www.2lvldomain.tld`. E.g. it should not be possible to allow `*.incomming.telemetry.mozzila.org`. Or even worse `*.mozzila.org` when dropdown is opened for `incomming.telemetry.mozzila.org`.

**Comment by dhaavi** [comment]
Hey @northys, thanks for the suggestion!

These buttons will get a revamp after the new network monitor is out. We will revisit how these buttons work then. I'm assigning @LukeSeers so he can keep this in mind when we get there.

I think this needs very careful consideration so that users really understand what they are doing.
