### ISSUE TITLE
Trim values before saving

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#221]
**What would you like to add or change?**:

Please trim values before saving. It throws errors when I copy settings time to time but it gets saved anyway and UI formats it like there is no issue but there is space at the start of last DNS which is impossible to notice.

![Screenshot from 2022-04-13 01-10-15](https://user-images.githubusercontent.com/2878126/163069260-7056fef0-d535-4601-9875-e3a854434002.png)![Screenshot from 2022-04-13 01-12-12](https://user-images.githubusercontent.com/2878126/163069258-e864bac5-6a9f-4a6b-b457-ec8ee7fb0c96.png)

**Why do you and others need this?**:

To keep our sanity.

**Comment by dhaavi** [comment]
Yes, that would make things easier. +1

Forwarding.

**Comment by ppacher** [comment]
This is fixed on the beta branch already
