### ISSUE TITLE
How to get rid of quick setup dialogue / introduction pop up

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#222]
**What would you like to add or change?**:

How can I get rid of this annoying welcome tour / quick setup dialogue? I'm afraid that it screws up my current configuration so I have to click on X to close it every time I open UI.

![Screenshot from 2022-04-14 14-05-15](https://user-images.githubusercontent.com/2878126/163387473-76d263fb-0bbc-4d89-af13-4908b9c12567.png)

**Why do you and others need this?**:

I think there are other people using portmaster for a long time who don't want to go through QUICK SETUP now.

**Comment by dhaavi** [comment]
We briefly talked about this today with the team. It seems there might have been some miscommunication about what exactly the "X" button does. Right now, it just dismisses the dialog and it will appear next time again.

If you want to get rid of it, just quickly click through the 4 steps - then it saves it as "seen".

**Comment by ppacher** [comment]
That behavior was on purpose so users that accide tally dismiss it will see it next time until they step through.it once. I guess we could add a "don't show again" checkbox to the first screen. But you can step through it without changing your settings

**Comment by northys** [comment]
That's okay. I was just afraid that it would change my settings to some defaults if I just go through it. Thanks for your reply. Now I don't have to worry about my config.

I would also expect that something like this don't pop up for 1year+ old installations. I would expect something like this when you add new feature. Some kind of basic onboarding just doesn't make sence at all for people who are using portmaster for a long time. It actually scarried me :D

**Comment by davegson** [comment]
> I would also expect that something like this don't pop up for 1year+ old installations. I would expect something like this when you add new feature. Some kind of basic onboarding just doesn't make sence at all for people who are using portmaster for a long time. It actually scared me :D

yeah this was a tough call for us. On the other side, there are a lot of people who installed PM recently like a month ago and some of them did not even know that PM configures DNS. We thought it was a better call to over-inform so even old installs had to go through it.

Also, I feel this issue can be closed as all _new_ installs - even experts setting it up on a second device - can just quickly click through it. Or what are your thoughts @northys?
