### ISSUE TITLE
SPN login button in notification doesn't work

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#224]
**What happened**:

![image](https://user-images.githubusercontent.com/2878126/163583871-da7167c6-eea5-4c71-98c3-bdd8c6095ec5.png)

**What did you expect to happen?**:

Login button opens login popup or something.

**How did you reproduce it?**:

Rebooted to windows and connected to SPN. It looks like my login / token expired. I clicked the login button in the notification widget but nothing happened.

**Debug Information**:

https://support.safing.io/privatebin/?76ad7e78cfdc8612#6roJzzPJNQGpcQ1f66ohP7hWpUQ63husnRNKBfb7mBUE

**Comment by LukeSeers** [comment]
I can personally confirm this too, since I had the same problem earlier today.

**Comment by ppacher** [comment]
Thanks for the report. I already have an idea of what's up there :)

**Comment by ppacher** [comment]
This page has been revamped and updated (on the `Beta` release channel right now). I'll close this for now. If it still happens please re-open
