### ISSUE TITLE
SPN account details refresh button should be disabled when login expires

### ISSUE THREAD

**Issue by northys** [safing/portmaster-ui#225]
**What happened**:

![image](https://user-images.githubusercontent.com/2878126/163584523-dda077e0-8f4a-41eb-96bd-0fdc2f0adf1b.png)

**What did you expect to happen?**:

I would expect that refresh button is disabled when SPN login expires.

**How did you reproduce it?**:

Let SPN login expire and try to use it.

**Comment by northys** [comment]
I would expect to see that red warning over half of my display. Also portmaster should not allow me to see it and it should display login form immediately.

This is unsolved edge case, doesn't break core functionality.

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
If your issue has not yet been resolved pleas create a new issue here:https://github.com/safing/portmaster/issues/new/choose
