### ISSUE TITLE
DNS Server Quick Settings Shouldn't Overwrite Entire Config

### ISSUE THREAD

**Issue by Bilibox** [safing/portmaster-ui#228]
**What would you like to add or change?**:

When choosing a quick setting it should not overwrite the entire config of DNS servers. Instead the "quick settings" values should only be changing it's own values.

**Why do you and others need this?**:

If you create an entire config it can be entirely wiped out with a press of a button. User values and System values should differ.

**Comment by dhaavi** [comment]
Hey @Bilibox, thanks for the good suggestion.

I haven't though about it in that way yet.
Much of this is expectation management, I guess.

I'll talk with the Team and see if there is good way to solve this.
