### ISSUE TITLE
Backwards animations when viewing apps

### ISSUE THREAD

**Issue by Bilibox** [safing/portmaster-ui#229]
**What happened**:

While viewing an app, when you select the different options (Connections, Settings, Details) the animations appear backwards.
When you are viewing Connections and select Settings, the UI slides in from the left. 
When you are viewing Settings and select Connections, the UI slides in from the right.

**What did you expect to happen?**:

The UI animation should be in line with how the options are set up. When going to the left, the UI should be popping in from the left. When going to the right, UI  should be popping in from the right.

**How did you reproduce it?**:

View "What Happened".

**Comment by dhaavi** [comment]
Hey @Bilibox, thanks for raising this issue.

I will look into it with @ppacher.

(Sorry for the assignee mis-click.)

**Comment by ppacher** [comment]
This one has already been fixed but we forgot to close it.
