### ISSUE TITLE
Shutdown in Settings is too hard to find.

### ISSUE THREAD

**Issue by Bilibox** [safing/portmaster-ui#230]
**What would you like to add or change?**:

The "Shutdown" option in Portmaster settings is far too hard to access. With no knowledge of the app before hand and the only hint is that it is "in the settings" when exiting the UI, It's too hard to try to find when hidden in a menu.
Searching for "Shutdown", "Exit", "Quit" shows no results due to the shutdown button being hidden within a menu.

This should have a dedicated button in the settings, or have a settings category dedicated to system functions (Restart, shutdown, reload ui). This way it is searchable and more easily found.

**Why do you and others need this?**:

Trying to search for a way to shutdown the app for 5 minutes is ridiculous and not user friendly. Since the tray notifier is broken for me (safing/portmaster-ui#232) and the only option is going through the settings, I was dumbfounded when I couldn't find something as simple as how to quit the application.

**Comment by LukeSeers** [comment]
Thank you for creating a issue ticket :)
This problem has now been improved in the latest version of the Portmaster. 

If you look at the bottom left you'll find:
![Shutdown](https://safing.io/assets/img/blog/release-0.9/4_2_shutdown.png "Shutdown")

If you think there is still a problem, please reopen this issue ticket
