### ISSUE TITLE
global live mode

### ISSUE THREAD

**Issue by Frostedfox** [safing/portmaster-ui#231]
**What would you like to add or change?**:
enable live mode for connections globally

**Why do you and others need this?**:
its kinda repetitive to enable live mode individually for every app you open

**Why do you and others need this?**:

**Comment by dhaavi** [comment]
Hey @Frostedfox, thanks for the suggestion!

We are currently rebuilding the whole network monitor, so I'll assign @ppacher, so he can take this into account.

**Comment by itsnotsaved** [comment]
@Frostedfox what kind of feature is this? how does that works?
"live mode for connections globally", "live mode individually for every app"

Or does that mean user doesn't need to press reload button for see new connections?

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
If your issue has not yet been resolved pleas create a new issue here:https://github.com/safing/portmaster/issues/new/choose
