### ISSUE TITLE
Inconsistency in Windows Service Manager

### ISSUE THREAD

**Issue by PDDStudio** [safing/portmaster-ui#234]
**What would you like to add or change?**:
Not sure if intended, but the `stopService()` implementation for the [Windows Service Manager](https://github.com/safing/portmaster-ui/blob/develop/app-electron/src/sm-windows.ts#L40) looks like a c&p issue.

**Comment by dhaavi** [comment]
Hey @PDDStudio, thanks for reporting this!

Yes, you are right. That does not look correct.
Afaik, we don't currently stop the Portmaster in that way from the UI, so this code is currently unused.

Assigning @ppacher to further look into this. (Might take a while.)
