### ISSUE TITLE
Notification buttons don't do anything

### ISSUE THREAD

**Issue by Vaelek** [safing/portmaster-ui#237]
### What happened?
Notification pops up, click Allow, nothing happens. It stays in the list on the left side of the app, and never gets added to the list.

### What did you expect to happen?
It would be removed from the left side and added to the app settings

### How did you reproduce it?
Click a button on the notification

### Additional information
This is on Windows 11 stable channel

**Debug-Info**: https://support.safing.io/privatebin/?bd566488f7dabb35#G9a2iiyKgcwJm7E1DAQxCahqsYxsXfQ1Gyouf5g9ZPYL

**Comment by dhaavi** [comment]
Hey @Vaelek, thanks for reporting this.

I will check if I can reproduce this.

**Comment by tobi1449** [comment]
Same here on Windows 11

**Comment by Kiefy** [comment]
You mean it works for some people?

**Comment by Kiefy** [comment]
Same on Windows 10.

Has always been this way. I thought it was just low priority work in progress.  Are you saying it actually works for some people?
