### ISSUE TITLE
Hardware Acceleration

### ISSUE THREAD

**Issue by y0himba** [safing/portmaster-ui#238]
**What would you like to add or change?**:
The option to turn off hardware acceleration on Windows. Not sure if this is a bug or a common issue amongst applications which use it.

**Why do you and others need this?**:
Not sure if this is a bug or a common issue amongst applications which use it, but sometimes hardware acceleration causes a blurry distorted interface, making it hard to read.

Making it optional would help alleviate this issue. 
![image](https://user-images.githubusercontent.com/11462603/171971686-68f2d5e9-0b2b-4e58-8119-18190a887444.png)
![image](https://user-images.githubusercontent.com/11462603/171971741-a8f779af-88cd-49a4-b1e5-5485d93a8b24.png)
(Portmaster blocked it's own interface?)

**Comment by dhaavi** [comment]
Hey @y0himba, thanks for reporting this!

I don't think that hardware acceleration is even enabled.
Can you check which command line options Portmaster App is started with? You should be able to find out via the task manager.

Are you using a HiDPI screen/setting?
The blur might be from the scaling.

**Comment by sperglord8008s** [comment]
Same issue here 
![2022-06-19 21_28_21-Portmaster](https://user-images.githubusercontent.com/54192936/174478827-5874baf1-f3d0-4773-abe0-4907192341f1.png)

**Comment by sperglord8008s** [comment]
Turn off FXAA in Nvidia Control Panel's global settings or make an exception for Portmaster executable.

**Comment by dhaavi** [comment]
Hey @y0himba, were you able to resolve this either by changing the HiDPI or the Nvidia settings?
