### ISSUE TITLE
 /ui/modules/portmaster/app/overview does not exist.

### ISSUE THREAD

**Issue by dimike96** [safing/portmaster-ui#239]
### What happened?
Occasionally when returning to the main menu / screen / default view from the details on an app/connection/settings a error prompt pops up with the title text. &#34; /ui/modules/portmaster/app/overview does not exist.&#34;

### What did you expect to happen?
No random errors describing missing files

### How did you reproduce it?
Interact with the ui for a while moving between setting such as rules, the all apps view, and the overview. It seems to happen randomly when moving from settings to the overview/apps screen. 

### Additional information

**Debug-Info**: https://support.safing.io/privatebin/?35aa0b8de27e7d33#5RYeTTNEJpu3y5Hjx8JDB9E4W7epVHjhVMGuXo9NQ9Ep

**Comment by dhaavi** [comment]
Hey @dimike96, thanks for reporting this!

This is weird. I am not sure what is happening here.

Did you possibly mistakenly issue a drag+drop action?
Also, is the space in the quoted message on purpose?

@ppacher might have an idea what is up here.

**Comment by dimike96** [comment]
I wish I took a screenshot to verify, but I'm not sure whether the space was there or not. It happened a handful of times before I reported but since I've poked around seeing if I can reproduce it but I haven't been able to. Feel free to close this if it was just a temporary problem only affecting me

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
