### ISSUE TITLE
System try icon gone, notifier working

### ISSUE THREAD

**Issue by PixsaOJ** [safing/portmaster-ui#240]
**What happened**:

Portmaster icon is gone from tray icons. Sometimes I see blank icon of something. It stays for couple seconds and after it deletes itself.

**What did you expect to happen?**:
To have system try icon shown.

**How did you reproduce it?**:
Probably installing latest Manjaro Gnome edition?

**Debug Information**:

```
Portmaster
version 0.8.13

commit tags/v0.8.13-0-gf135ec3242905b84811b26975a3458117cc2c28e
built with go1.18 (gc) linux/amd64
  using options main.go
  by user@docker
  on 01.06.2022

```

I am deducting everything else in logs because its too big and I did not find related info. It probably happens on boot time.'

I am on Manjaro Gnome edition.
GNOME Shell 42.1
Also using extension called Try Icons to hide them.

This might need better debug log, let me know.

All the notifications are working BTW.

**Comment by dhaavi** [comment]
Hey @PixsaOJ, thanks for reporting this!

Can you run this command to start the notifier manually and then post the output?
`/opt/safing/portmaster/portmaster-start notifier`

You might need to close the currently running one in some way.

**Comment by PixsaOJ** [comment]
@dhaavi seems like it assumed that I'm on KDE because it's Manjaro or something.

**Comment by arch-user-france1** [comment]
> **What happened**:
> 
> Portmaster icon is gone from tray icons. Sometimes I see blank icon of something. It stays for couple seconds and after it deletes itself.
> 
> **What did you expect to happen?**: To have system try icon shown.
> 
> **How did you reproduce it?**: Probably installing latest Manjaro Gnome edition?
> 
> **Debug Information**:
> 
> ```
> Portmaster
> version 0.8.13
> 
> commit tags/v0.8.13-0-gf135ec3242905b84811b26975a3458117cc2c28e
> built with go1.18 (gc) linux/amd64
>   using options main.go
>   by user@docker
>   on 01.06.2022
> ```
> 
> I am deducting everything else in logs because its too big and I did not find related info. It probably happens on boot time.'
> 
> I am on Manjaro Gnome edition. GNOME Shell 42.1 Also using extension called Try Icons to hide them.
> 
> This might need better debug log, let me know.
> 
> All the notifications are working BTW.

This is a gnome issue. You should report it there. It works fine on my Manjaro Gnome laptop but not on the desktop computer.

**Comment by PixsaOJ** [comment]
> This is probably a gnome issue. You should report it there. It works fine on my Manjaro Gnome laptop but not on the desktop computer.

I disagree. The program is searching KDE notifier watcher while it should be watching Gnome thing.
Also, there is no difference between laptop/desktop when it comes to OS. Only drivers are different, which is not problem in this issue.

**Comment by arch-user-france1** [comment]
I know that there's no difference but I installed KDE first and then Gnome, on my laptop I had Gnome preinstalled. That is a difference.

> > This is probably a gnome issue. You should report it there. It works fine on my Manjaro Gnome laptop but not on the desktop computer.
> 
> I disagree. The program is searching KDE notifier watcher while it should be watching Gnome thing. Also, there is no difference between laptop/desktop when it comes to OS. Only drivers are different, which is not problem in this issue.

**Comment by arch-user-france1** [comment]
> Yes, it does not work on GNOME but that does not mean its GNOME's fault

It does work on gnome on my laptop.

It does not work on gnome on my desktop computer which had kde installed first but now has gnome.

**Comment by PixsaOJ** [comment]
It is possible to install "AppIndicator and KSattusNotifierItem support" extension but that just breaks my setup, It is hacky fix. I would not recommend. Better to have Gnome 42 support.

**Comment by dhaavi** [comment]
Hey @PixsaOJ, thanks for logs! Also, thanks @arch-user-france1 for helping out here!

What you saw with `org.kde.StatusNotifierWatcher` is just the namespace used for the tray icon. The libappindicator library uses the same namespace.
This is the DBUS location where an appindicator system can register in order to handle app indicators for apps.

The error you receive seems to be caused by the appindicator system being missing.

Gnome stopped shipping with one by default some time ago. Ubuntu then started to shipping this for their Gnome DE instead: https://github.com/ubuntu/gnome-shell-extension-appindicator (Works great!)
