### ISSUE TITLE
Portmaster UI becomes blurry - Win10

### ISSUE THREAD

**Issue by sperglord8008s** [safing/portmaster-ui#241]
Portmaster UI becomes blurry - Windows 10 install with 2560x1080 display resolution , 1060GT with latest NVIDIA drivers 

Not sure if this is normal or a known issue 
![2022-06-19 21_28_21-Portmaster](https://user-images.githubusercontent.com/54192936/174478733-8ec92bac-f32a-4838-a46b-60fcab89fcab.png)
 
 
 If you need any other details or a log or something just lmk

**Comment by dhaavi** [comment]
I think this is a duplicate of #238, if you can confirm, please close this in favor or #238.

**Comment by sperglord8008s** [comment]
Closing, Duplicate + Found issue was FXAA turned on as global settings in Nvidia Control Panel
