### ISSUE TITLE
Move the second panel to a 'Notification Like' UI.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#251]
![image](https://user-images.githubusercontent.com/62152714/177803672-831e397d-c9f2-4a74-b8e3-f92587984bb2.png)
![image](https://user-images.githubusercontent.com/62152714/177804364-621d616b-8232-4a48-8a08-83e8ef85e0e0.png)

**Comment by dhaavi** [comment]
If I understand you correctly, we are moving in that direction.

**Comment by Rexadev** [comment]
@dhaavi I mean instead of a panel use a notification button that shows-hides notification-panel

**Comment by Rexadev** [comment]
@dhaavi I tried the new UI and it is not a part of it. So please reopen this issue
