### ISSUE TITLE
Move Left panel to a 'Hamburger Menu'

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#252]
![image](https://user-images.githubusercontent.com/62152714/177804614-2f275ea7-4b08-43e8-b67d-6db9309e5683.png)

**Comment by dhaavi** [comment]
Good idea on saving space, however, we will be moving more stuff into there to save space elsewhere.

**Comment by Rexadev** [comment]
@dhaavi How about making is collapsible?
