### ISSUE TITLE
Settings/rules Sidebar - UI and Rearrange categories 

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#253]
### Rearrange  -

~Rename Secure DNS to DNS~
~Rename Privacy Filter to Filter~
~Rename Connection Type to Connection Security~

Merge Core and General
Move General Out  to seperate category
Move DNS filtering to Secure DNS
Move Privacy Filter/Advanced to Secure DNS
Move DNS filtering to 

Merge Secure DNS/Servers and Secure DNS/Resolving

Move "IPsum Threat Intelligence Feed" to security List

### UI -

Use Pages instead on scroll positions

Privacy is the biggest section. Always keep all categories expanded. And show headers in bolder UI, 

with lines Portmaster UI doesn't use lines looks futuristic but also messy

Use empty space

![image](https://user-images.githubusercontent.com/62152714/178223795-c3b5599e-ecf6-4098-8e09-3eeae2f24b44.png)

**Comment by davegson** [comment]
Hey there,

we know the UI still can be improved - and you got some good ideas there.

But first off:

> Rename Secure DNS to DNS
> Rename Privacy Filter to Filter
> Rename Connection Type to Connection Security

this will not happen.

However, we will revisit these sections sometime in the "Beta" phase. Reordering the sections and potentially merging some is definitely a thing we will consider once we get to it.
