### ISSUE TITLE
[Notifications] FAQ + Check if Windows is preventing notifications

### ISSUE THREAD

**Issue by cocoon** [safing/portmaster-ui#260]
**What would you like to add or change?**:

Add a check at setup, start or in intervals if windows is configured to prevent notifications.

**Why do you and others need this?**:

It might help your and users troubleshooting if they don't get any notification popups.

From my initial first try with portmaster I was not getting notifications at all, because I have configured Windows to use a priority list for notifications and I have to add programs manually to a list.

The feature in Windows is called "Focus Assist" in english. If you configure it to "priority only" you have to manually add portmaster to the list to get notification popups.

So maybe there is a way to check within the setup (and even maybe when portmaster is starting each time) if windows is configured like this and tell the user about it / log it.

**Comment by dhaavi** [comment]
Hey @cocoon, thanks for the suggestion!

I will assign @vlabo, so he can take a look if that is possible.

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
