### ISSUE TITLE
Small Ui bug when using the breadcrumbs element in Per App settings

### ISSUE THREAD

**Issue by mignat** [safing/portmaster-ui#283]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/portmaster-ui/issues?q=is%3Aissue+label%3Abug)

**What happened**:
I receive an error message when i try to return to the *All apps* menu using the breadcrumbs ui element on any application page

**What did you expect to happen?**:

Return to the *all apps* page without the error message

**How did you reproduce it?**:

1. Open PostMaster-ui
2. Go to All Apps from the sidebar 
![image](https://user-images.githubusercontent.com/30924447/183295408-eb4d2c01-e88f-436c-a16b-829089400502.png)
3. Open any app from the right hand side
4. Click on the *Apps* Breadcrumb element
![image](https://user-images.githubusercontent.com/30924447/183295570-c921fb97-6880-479c-a83e-0bff4fabb881.png)
5. Receive this error message after whitch everything works
![image](https://user-images.githubusercontent.com/30924447/183295973-1df8ebd3-3e0d-4cc8-8d8b-de1ebcdfa90a.png)

**Debug Information**:
OS: Arch Linux x86_64
Kernel: 5.18.16-arch1-1
Resolution: 3840x1600
DE: Plasma 5.25.4

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
If your issue has not yet been resolved pleas create a new issue here:https://github.com/safing/portmaster/issues/new/choose
