### ISSUE TITLE
Shrink Left Panel

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#284]
![image](https://user-images.githubusercontent.com/62152714/184477246-69dfa223-2b77-41e4-88b9-88c33fd20c32.png)

**Comment by dhaavi** [comment]
Even smaller? Why?

**Comment by Rexadev** [comment]
and use all space available

**Comment by LukeSeers** [comment]
Shrinking the navbar is not a ideal solution for freeing up more space. We'll be using the navbar to compact UI elements into it thus will create alot of free space in the ui.

I will close this ticket, but if you have anymore ideas about the navbar please reopen this ticket.
