### ISSUE TITLE
UI Changes to save space in Network Activity Page

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#285]
![image](https://user-images.githubusercontent.com/62152714/184478560-a7cbd540-a807-4479-856b-6e74768c1141.png)
![image](https://user-images.githubusercontent.com/62152714/184478754-902f9031-a2da-4193-9944-15296e6daa65.png)
2 search bars
1. Remove Titlebar
2. Does nothing
3. Move with title
4. Move down

**Comment by LukeSeers** [comment]
Thank you for your suggestions. When we start to clean up the UI more in the Portmaster we will revisit this issue ticket.
