### ISSUE TITLE
Show Flag and hover Full Name of Country and ISO instead of only ISO code

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#286]
![image](https://user-images.githubusercontent.com/62152714/184478613-bb0b072d-7909-4f7c-b764-ed5625411e9c.png)

Maybe not flags some flags are bad like Australia and new Zealand have same flag.

**Comment by dhaavi** [comment]
I like that one. Let's see what @LukeSeers thinks about this.

**Comment by LukeSeers** [comment]
Thanks @Rexadev for this suggestion/reminder. This was one of the ideas we had a while back, but it seems to have gotten lost in the mix of things.

I've now created a task in CC **2529** to keep track of it for the future.

**Comment by tukusejssirs** [comment]
A country name in a tooltip would be nice too, as not everyone knows all ISO codes and/or flags for all countries.

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
