### ISSUE TITLE
Showing svchost connection inside of Firefox page

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#288]
![image](https://user-images.githubusercontent.com/62152714/184479399-f977f04e-ce3a-49e9-9ebf-cf0a0f830668.png)

**Comment by dhaavi** [comment]
Whoops. This should not happen.

**Comment by ppacher** [comment]
I cannot reproduce this. Can you please check if you find a reliable way to reproduce the issue. 
Also, please start filling out the issue templates because the debug information (that you always omit to provide) would help a lot here ....

**Comment by Rexadev** [comment]
>  Can you please check if you find a reliable way to reproduce the issue.
No

**Comment by ppacher** [comment]
> No

Than we can sadly not help you ...
