### ISSUE TITLE
Save space on app page

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#290]
![image](https://user-images.githubusercontent.com/62152714/184479634-083e9486-08df-4809-bffa-abbec34653ba.png)

1. Remove
2. Remove
3. Move Right and Up and make it smaller
4.  and 5. Make it smaller and move it to right and Up with Big App Tittle

**Comment by LukeSeers** [comment]
Thank you for the issue ticket. When we get to polishing the UI we'll reference this ticket.
