### ISSUE TITLE
Misaligned text in Connection list. Updated v0.9.5

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#292]
![image](https://user-images.githubusercontent.com/62152714/184480021-4d30c9e2-2343-4c7c-ada5-b2c7dac42722.png)
1. Unused Space
2. Missing Text
3. Miss Aligned
4. Space
5. What is "f"

# Update
![image](https://user-images.githubusercontent.com/62152714/190924133-515f9140-0585-4e64-a0ff-72447cf3d801.png)

## When Panel Closed
![image](https://user-images.githubusercontent.com/62152714/192132857-48d6e68f-10fd-41f0-8f31-6fcde848dc03.png)
![image](https://user-images.githubusercontent.com/62152714/192132861-65f786b9-8fdd-43e0-8c0e-134a5dc1a81a.png)
## When Panel Open
![image](https://user-images.githubusercontent.com/62152714/192132840-6a0b2897-9d57-46db-90ad-34403e8ed4dd.png)

**Comment by dhaavi** [comment]
Yea, this seems like it could be improved.

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/190924133-515f9140-0585-4e64-a0ff-72447cf3d801.png)
