### ISSUE TITLE
Indication on filter list settings if only a part of the filter list is activated

### ISSUE THREAD

**Issue by Cmnspro** [safing/portmaster-ui#296]
**What would you like to add or change?**:
Some kind of indication if, for example only the "Windows Spy Blocker" List from the "Experiments" category is activated, and the list with the sub categories is collapsed, there is no indication if any sub filter lists are activated.

**Why do you and others need this?**:
I believe there should be some kind of indication to let the user know that one or more sub lists are active, without having to expand all of them.

![filtersettings](https://user-images.githubusercontent.com/54321931/185144432-645f9443-0ef0-43a2-aae6-30a58c52799b.PNG)

**Comment by dhaavi** [comment]
I think we already had that. Might be a regression.
@ppacher?

**Comment by ppacher** [comment]
An improvement for that is already on the Beta release channel. Closing this for now. If you feel the solution (a blue dot before the checkbox) is not enough please re-open
