### ISSUE TITLE
"Apps" label errors "/ui/modules/portmaster/app/overview"

### ISSUE THREAD

**Issue by 0x454d505459** [safing/portmaster-ui#297]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/portmaster-ui/issues?q=is%3Aissue+label%3Abug)

**What happened**:

In any app section, pressing the `Apps > APP_NAME` to go back to the apps overview throws an error `file or directory: /ui/modules/portmaster/app/overview doesn't exists` but still goes back to the overview.

**What did you expect to happen?**:

Expected it to go back to the app overview without giving back any errors

**How did you reproduce it?**:

Open any per-app setting and go back by pressing `Apps >` in the top left corner of the "main" panel (the div with the **main** class)

**Debug Information**:

[debugInfo.txt](https://github.com/safing/portmaster-ui/files/9365034/debugInfo.txt)

**Comment by dhaavi** [comment]
Hey @0x454d505459, thanks for the report!

**Comment by 0x454d505459** [comment]
Looks like it was patched in an update. Thanks
