### ISSUE TITLE
Show blocked reason and block when hovering over and show full blocklist names.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#298]
![image](https://user-images.githubusercontent.com/62152714/177802838-d1d68d7b-3f4e-455d-9278-9a620be6ded7.png)

Red circle is where user would hover

3rd image is example on how to use full names of blocklists instead of abbrivations

**Comment by ppacher** [comment]
The tooltip showing the allow/block reason is already on the Beta release channel. Showing the full names of the blocklists is more work though and might happen at a later point. I'm closing this for now

**Comment by Rexadev** [comment]
@ppacher If this is changed then might want to close this https://github.com/safing/portmaster-ui/issues/279
