### ISSUE TITLE
Rearrange Network Scope filter

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#300]
![image](https://user-images.githubusercontent.com/62152714/185416379-05f5f7cf-6658-429d-8898-e6c58c2c3717.png)
![image](https://user-images.githubusercontent.com/62152714/185416407-46482210-ff4b-41a6-8a6d-58f8f8fd1dc5.png)

I Suggest 

```
- Internet
- Internet Multicast
~~~ _Separator_~~~
- Invalid
- Undefined
~~~ _Separator_~~~
-  LAN
- LAN Multicast
~~~ _Separator_~~~
- Device Local
- Link Local
 ```

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
