### ISSUE TITLE
Add symbols for More Filter, Rename Filter by * to *, Remove Empty Space

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#301]
![image](https://user-images.githubusercontent.com/62152714/185417718-46c64e78-aea3-4c22-ac73-6f13141daa94.png)

### More Suggestions - 

Add lines after header
Add lighter lines between options

### Symbols - 

For Active - Circle filled and Ring

For Direction - Up and Down Arrows

For Scope - 

- Internet - Globe
- For LAN - https://www.google.com/search?q=LAN+symbol
- Multicast - https://www.google.com/search?q=multicast+symbol

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
