### ISSUE TITLE
Overflowing/Overlapping Texts

### ISSUE THREAD

**Issue by psycho-neon** [safing/portmaster-ui#302]
**What happened**: Some of the text in UI in the networking monitoring are overflowing/overlapping.

**What did you expect to happen?**: Text should automatically wrap around the allowed limit only.

**How did you reproduce it?**:

**Screenshot**:
https://prnt.sc/6C9Ov3643AhY

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
