### ISSUE TITLE
[FeatureRequest] GUI map: Make it easier to block countries

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#304]
There are 195 countries in the world if I want to block or allow half of it. It is very hard.
Hosting is located mostly in US, UK, Canada, Aus, Germany, France, Russia, Japan, the country of the user. For most English speakers only allowing USA will work 90% of the times.

Related: https://github.com/safing/portmaster/issues/724

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
