### ISSUE TITLE
Show Icon for OS Components - Operating System, Network Noise, System DNS Client, Unidentified Apps...

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#306]
![image](https://user-images.githubusercontent.com/62152714/186495887-7146dfc7-11d7-4b45-93a9-d92faa3a47b2.png)
![image](https://user-images.githubusercontent.com/62152714/186496653-50e149da-25cd-43c4-a004-76f7a17579f9.png)
![image](https://user-images.githubusercontent.com/62152714/186497449-e4127ff4-2be7-4d2d-b084-338c01ead19e.png)
![image](https://user-images.githubusercontent.com/62152714/186497604-12b94877-bf1c-4cfd-869a-cf6d5fab3929.png)
![image](https://user-images.githubusercontent.com/62152714/186498003-1cc4c53e-365d-4d48-a2e5-cf00ce9d8a5d.png)

**Comment by ppacher** [comment]
Obviously those binaries do not have an icon associated so I'm not sure what we should show there. Guessing an icon just because it's under some `Microsoft` path seems to open up a can of worms for faking a process icon to look like it's from MS.

Do you have any suggestions on that @Rexadev?

**Comment by Rexadev** [comment]
> Do you have any suggestions on that @Rexadev?

Hardcode icons for OS processes

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
