### ISSUE TITLE
Rename svchost.exe from System DNS Client to "Windows Component - svchost.exe" and more

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#307]
- Windows Component - svchost.exe with `i` button to tell what it does.
svchost.exe does many things not only "System DNS Client"

- Add "Windows Component - Windows Defender - " to Microsoft Network Realtime Inspection Service

![image](https://user-images.githubusercontent.com/62152714/186496860-7f35dd82-21d1-4572-9648-7ec1b4bede7f.png)

- Add "Windows Component - "to WWA Host

**Comment by dhaavi** [comment]
Currently, only the `Dnscache` service gets their own Profile with the `System DNS Client`.

All other svchost services share a profile, whose name is extracted from the binary and should be OK.

I'll think about splitting this up more, but this is difficult, as one svchost.exe might have multiple services in it. This is a pretty ugly system and it is not easy to make it nice.
