### ISSUE TITLE
No Icons in some 3rd party apps

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#308]
Glasswire
![image](https://user-images.githubusercontent.com/62152714/186498282-f55cb86f-4f77-4325-8300-7d84e43a2931.png)
![image](https://user-images.githubusercontent.com/62152714/186498346-50f0798a-6e9e-4b3c-a27b-948988b6502a.png)
![image](https://user-images.githubusercontent.com/62152714/186498376-c5b97a94-eeb5-4a07-8884-a3f2e2e8f82c.png)
MP3Tag
![image](https://user-images.githubusercontent.com/62152714/186498445-c710c431-02df-4eb6-9ac5-0348062c607d.png)

foobar2000
![image](https://user-images.githubusercontent.com/62152714/186498424-685eaf34-611e-4aa7-b63b-4bad337f173b.png)
![image](https://user-images.githubusercontent.com/62152714/186498912-be08085b-679e-4ac1-89aa-168486f3f5fe.png)

![image](https://user-images.githubusercontent.com/62152714/186498625-fdbb73ef-0857-4d56-8b6e-b3f24aafcffb.png)

Nahimic
![image](https://user-images.githubusercontent.com/62152714/186499055-7771d367-b412-4a16-a559-7e6d563633f7.png)

**Comment by dhaavi** [comment]
Icons are loaded by electron, not us. We can't do anything here until we start doing the icons ourselves. Which is a pain and won't happen soon.
