### ISSUE TITLE
App Icon missing from 2nd panel

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#320]
![image](https://user-images.githubusercontent.com/62152714/188390646-f3b6e73c-e84f-47a0-a1c7-2d09eefc5324.png)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/portmaster-ui/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
