### ISSUE TITLE
Regression: connection attempts require an extra click

### ISSUE THREAD

**Issue by working-name** [safing/portmaster-ui#322]
**What would you like to add or change?**:
I would like the connection attempt notifications to be restored to its initial location. Right now it requires an extra click, and on windows where the native notifications do not do anything (clicking does nothing, clicking allow does nothing, clicking deny does nothing) it's even more critical.

If possible maybe make it open like the SPN status sidebar? Use the whole height of the app to display the requests.

**Why do you and others need this?**:
I would like to avoid having to activate the app, and then click the tiny triangle icon on its sidebar to see a tiny window listing connection requests.

**Comment by dhaavi** [comment]
There are a couple changes incoming here. I will assign @LukeSeers to fill in the details.
