### ISSUE TITLE
Remove uninstalled apps from dashboard. Or Show deleted apps or their profiles in red tint and option to deleted them from dashboard

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#332]
![image](https://user-images.githubusercontent.com/62152714/177805564-ffaedd31-1db5-4827-bcc6-8baac3a15c59.png)

![image](https://user-images.githubusercontent.com/62152714/186497285-4c452cb0-da69-4ac3-9412-b9b8aedbbbee.png)

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
