### ISSUE TITLE
[Fixed] Misaligned dots in connection list

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#333]
![image](https://user-images.githubusercontent.com/62152714/190924042-ee33aece-7d24-48c2-bd7d-ec525d1f13cb.png)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/portmaster-ui/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by ppacher** [comment]
This should already be fixed on the beta release channel
