### ISSUE TITLE
Removed force block and show blocked allowed in toggle

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#334]
![image](https://user-images.githubusercontent.com/62152714/191048984-095e57f9-d1d5-4de2-b229-4c04a566b1af.png)

**What would you like to add or change?**:

**Why do you and others need this?**:

**Comment by ppacher** [comment]
That wording was on purpose because those settings are even stronger than rules

**Comment by Rexadev** [comment]
> That wording was on purpose because those settings are even stronger than rules

I understand What I am suggesting is UI changes. 
Show Allow and Block Left and Right of the toggle.
