### ISSUE TITLE
9.0.5 - Drop down weird

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#336]
### 5 Drop Down Box Misaligned
![image](https://user-images.githubusercontent.com/62152714/192088887-32bb6ab3-cce5-4226-b4b8-0703da3e8374.png)
![image](https://user-images.githubusercontent.com/62152714/192088889-37c0a719-3e46-434e-a459-0439c2b06746.png)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/portmaster-ui/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
I think most of this will be fixed in the next update to Beta tomorrow.

**Comment by dhaavi** [comment]
Update will hit Beta on Monday.

**Comment by Rexadev** [comment]
> I think most of this will be fixed in the next update to Beta tomorrow.

Only 1 issue fixed

**Comment by Rexadev** [comment]
@dhaavi drop down still buggy in 1.0.2

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
