### ISSUE TITLE
Add option to group countries and domains together

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#337]
In Most use cases Firewall blocklist is in this order -
1. Countries
2. CIDR (maybe handled as blocklist rules instead)
3. TLDs (maybe handled as blocklist rules instead)
4. Domains
5. IPs

Most people will not touch country blocklist because user adds it knowing whose will rarely be used. It will be nice to make it collapsible.

Related: https://github.com/safing/portmaster-ui/issues/304

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
