### ISSUE TITLE
Left click on Icon should open the UI and right click should show context menu

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#338]
Now left or right it show menu

**Comment by dhaavi** [comment]
Which icon?

**Comment by Rexadev** [comment]
> Which icon?

Windows system tray on bottom right

**Comment by Kiefy** [comment]
I just wrote up a lengthy submission asking for exactly the same thing before I noticed somebody had already requested it.

One thing that's worth bringing up:
When you get a connection pop-up, it obscures the tray menu right click menu, so you either have to accept/dismiss all the notification pop-ups before you are able to open the main gui.  Allowing left-click to open the GUI would solve this issue, and who knows. it may still work when the right-click menu bugs out. as it **so very often** does.

**Comment by e-t-l** [comment]
Either a single left click, or a left double-click, would be helpful to open the Portmaster app. (Double-click would also align more with the typical behavior of most other Windows tray apps. Makes the UX more intuitive.)

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
