### ISSUE TITLE
Misalign Program name - More Space at bottom than at top

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#347]
### Example
Zoom it or look at your own portmaster
![image](https://user-images.githubusercontent.com/62152714/195293349-1b89e882-1b06-4bd6-a608-be236ea0d0ad.png)
![image](https://user-images.githubusercontent.com/62152714/195294134-98e1a9e4-d5e4-45aa-96f4-04f1ad1301cc.png)

1. Inside the icon too
2. 3. Comparison 3. is little off

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
