### ISSUE TITLE
Freeze Filter/Sort Options

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#349]
![image](https://user-images.githubusercontent.com/62152714/196018563-2e6d4dc9-a57e-4d05-963d-2408df3b0f05.png)

Move 2 below 3 and Freeze it

Related-
https://github.com/safing/portmaster-ui/issues/290 (Organize 1)
https://github.com/safing/portmaster-ui/issues/285 (Organize 3)

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
