### ISSUE TITLE
Move * Results of * total Connections, Freeze Page Number, Move Next/Previous Buttons

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#350]
![image](https://user-images.githubusercontent.com/62152714/196018779-70326bbe-f235-45f0-b193-4adc5180bd4c.png)
![image](https://user-images.githubusercontent.com/62152714/196018807-0bded5e1-a2b3-46e6-b75c-554fd4254701.png)
![image](https://user-images.githubusercontent.com/62152714/196018859-7eb911db-97df-4167-8d9f-6ac4f440689f.png)

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
