### ISSUE TITLE
Network Activity is showing data beyond 10 minutes and across reboot

### ISSUE THREAD

**Issue by Regalias** [safing/portmaster-ui#389]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/portmaster-ui/issues?q=is%3Aissue+label%3Abug)

**What happened**:

I seem to be running into a bug (?) where the UI is displaying connections from almost a day ago - see screenshot below:

![image](https://user-images.githubusercontent.com/8436419/209500339-866f862c-c9ea-4d09-882c-e7222cda081c.png)

Some of these displayed connections were made the previous day, and this data seems to have persisted beyond a reboot.

Opening the `Network Activity` tab in the Portmaster UI results in extremely high CPU usage and an unresponsive UI for ~15 seconds while it presumably processes the large amount of connection data (beyond the supposed 10 minute retention period) to generate graphs and such

**What did you expect to happen?**:
If I'm not mistaken, the Portmaster UI is only intended to show the last 10 minutes of network connections. 
(Going by open feature requests on #226 and https://github.com/safing/portmaster/issues/682)

**How did you reproduce it?**:
N/A

**Debug Information**:

Running on Portmaster version `1.0.4` on Windows 11

If debug info/logs are required, let me know how I can submit them in a non-public manner.

**Comment by tachion23** [comment]
Hello

It's exactly the same for me. Browser processes are closed in the task manager and appear in the program for a long time.

I would like, if possible, for processes or services to be displayed in real time or for this time to be minimized as much as possible.

**Comment by reijerh** [comment]
Same for me, this is making the connections list part of the UI unusable because it takes forever to load connections.
