### ISSUE TITLE
Lite client

### ISSUE THREAD

**Issue by Chief36** [safing/portmaster-ui#409]
**What would you like to add or change?**:
A lite client where features are served as modules/plugins will be helpful in cases where Portmaster seems to be a big resource hogger (as in my case). 

**Why do you and others need this?**:
Instead of bundling different modules such as SPN, blocklists, DNS etc. into a single app, they can be shipped separately so that the user has choice over which module they want to install and overall Portmaster will consume lesser resources. This can be called a lite client because it is not bloated 🙃. This is related to a similar issue opened less than an hour ago: https://github.com/safing/portmaster/issues/1122

**Comment by dhaavi** [comment]
Please elaborate what you mean with "resource hogger".

Portmaster on my system:
```
$ ps -p $(pgrep portmaster-core) -o %cpu,%mem,cmd
%CPU %MEM CMD
 1.2  2.9 /opt/safing/portmaster/updates/linux_amd64/core/portmaster-core_v1-0-7 --data /opt/safing/portmaster
 ```
 
Internally, the core service already uses modules. Eg. if you are not using SPN, the relevant systems are not even started.

Please also not that high memory usage (esp. with the SPN) stems from the Go runtime not immediately releasing memory back to the system for performance reasons. We hope that this is improved in the future.

**Comment by Chief36** [comment]
> Please elaborate what you mean with "resource hogger"

High memory and CPU usage was my problem here. 

> Please also not that high memory usage (esp. with the SPN) stems from the Go runtime not immediately releasing memory back to the system for performance reasons. We hope that this is improved in the future.

Alright.

**Comment by Chief36** [comment]
Anyways, if somebody for example, won't be needing SPN, why not just ship a client without that module? If the user, at any point in time, will be needing it, then they would be able to install it as a plug-in module.

**Comment by dhaavi** [comment]
This is pretty much what we are doing. If the SPN is disabled, the won't be even initialized, ie. it won't use any resources.

**Comment by Chief36** [comment]
However, the resource consumption is quite high for users like me. To give a rough idea of this, OpenSnitch daemon consumes about 81 MB of RAM and OpenSnitch UI consumes around 300 MB of RAM. Portmaster UI on the other hand consumes more than 500 MB of RAM while the daemon consumes 900 MB of RAM. Resource consumption is still very high for an application firewall. What else will Safing do to improve the perform and decrease resource consumption? And when will Portmaster stop messing up DNS?
