### ISSUE TITLE
Disable the shortcut F12 for opening devTools or change it

### ISSUE THREAD

**Issue by Zesko** [safing/portmaster-ui#414]
**What would you like to add or change?**:

I would like to change or disable the shortcut <kbd>F12</kbd> on Portmaster UI.

**Why do you and others need this?**:

If you use the _favorite_ shortcut <kbd>F12</kbd> to open a drop-down-terminal e.g. **ddterm** on Gnome Wayland, but Portmaster UI opens **devTools** at the same time because of the same shortcut <kbd>F12</kbd>.

Opening **devTools** applies to two possible shortcuts:  <kbd>F12</kbd>  or  <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>i</kbd>
That is why I do not need to use <kbd>F12</kbd> on Portmaster UI.

**Comment by Zesko** [comment]
https://github.com/safing/portmaster-ui/blob/6bd73e4d6597ec626ded033189493e0aa899dc94/app-electron/src/index.ts#L79

Is it possible to add a new option to disable or enable F12?

**Comment by Raphty** [comment]
this is due to it running in electron - which is basically a browser window.

Also the UI is not meant to be kept open, so this is not a priority.

Sorry
