### ISSUE TITLE
More room for editing rules per app

### ISSUE THREAD

**Issue by KDAM71** [safing/portmaster-ui#429]
**What would you like to add or change?**:

I'd like more room when I'm editing rules per app. At the moment I can only see 5 rules at a time. A separate window would  be fine by me.

**Why do you and others need this?**:

To have more of an overview of the rules.

**Comment by dhaavi** [comment]
There should be plenty space. Can you please post a screenshot?

**Comment by KDAM71** [comment]
![afbeelding](https://user-images.githubusercontent.com/128472955/235095756-c9e5e939-b388-4317-8267-eab411908fc6.png)

**Comment by ppacher** [comment]
Sorry for not replying earlier. You can use the "collapse header" button at the bottom-right of the chart on the application header.
