### ISSUE TITLE
Reset all profiles to default/global

### ISSUE THREAD

**Issue by OfficialEsco** [safing/portmaster-ui#441]
**What would you like to add or change?**:
I would like a button to reset all the profiles to default and/or global 

**Why do you and others need this?**:
I see a lot of people testing different things and are asking for a way to reset all the settings.

**Comment by OfficialEsco** [comment]
Does this mean the feature is added or not planed to be added?

**Comment by Raphty** [comment]
as mentioned in the other issue, I want to increase focus. as you saw in the latest beta, we are working towards fixing these issues at the moment

a button like this can also be super dangerous, as the work of many hours can be lost in seconds.

We might be revisiting something like this when import/export is implemented. for now I believe that the multi step process you helpfully described in this guide is the better option

https://wiki.safing.io/en/FAQ/ResetPortmasterSettings

if you disagree pleas comment and I will gladly reopen the issue.
