### ISSUE TITLE
[bug] No tray icon for i3 and Polybar

### ISSUE THREAD

**Issue by hbednar** [safing/portmaster-ui#448]
**What happened**:
After installing Portmaster using the deb package and starting the core, app and notifier. 
Everything seems to work but, there is no tray icon.

**What did you expect to happen?**:
There should be a tray icon for Portmaster next to all the other tray icons in polybar.

**How did you reproduce it?**:
Install using the deb package on the latest i3 and polybar, then start portmaster core, app and notifier.

**Debug Information**:

<!--
Paste debug information below:
I am not seeing any related errors, please let me know which logs are required.

**Comment by ppacher** [comment]
AFAIK i3 does not support the xdg-autostart specification (I'm on AwesomeWM and have the same issue). I guess you just need to make sure to start the notifier automatically when i3 launches. Something like the following in `~/.config/i3/config`:

```
exec /opt/safing/portmaster/portmaster-start notifier --data=/opt/safing/portmaster
```

**Comment by hbednar** [comment]
I tried starting the cor and then the notifier in the way you said but got this error.

`sudo /opt/safing/portmaster/portmaster-start core`
`/opt/safing/portmaster/portmaster-start notifier --data=/opt/safing/portmaster`

`systray error: failed to register our icon with the notifier watcher (maybe no tray is running?): The name org.kde.StatusNotifierWatcher was not provided by any .service files`
