### ISSUE TITLE
One click cleanup for obsolete profiles 

### ISSUE THREAD

**Issue by dunknownguy** [safing/portmaster-ui#449]
Hello Team,

I would like to see, the below features available:

1. Option to perform one click cleanup for obsolete profiles under Apps section, this is specifically the case for Linux systems, where the (. Appimages) create /tmp profiles for every launch and it keeps growing infinitely. unless we do a manual delete.

Additionally,
2. To differentiate between, enabled and disabled apps under Apps section, would like to see either a filter option(2) on the search bar(1) or differentiate apps by color or something on that line would be great. (refer img)

![PM-feature-requestq](https://github.com/safing/portmaster-ui/assets/135158679/dfc667e2-8a50-4e87-8916-8644b0445962)

Let me know your thoughts...
Thanks

**Comment by Terrance** [comment]
I'd also like to see this, or some way of multi-selecting apps for bulk actions -- currently it takes a search and 4 clicks to delete a single profile (select a profile → _Details_ → _Delete Profile_ → _Yes, Delete It_, and then back at the All Apps page the search query is cleared if used before), which makes tidying up temporary or duplicate app profiles a real pain.
