### ISSUE TITLE
Web interface not working with 1.4.3

### ISSUE THREAD

**Issue by dahkara** [safing/portmaster-ui#474]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Github Issues](https://github.com/safing/portmaster-ui/issues?q=is%3Aissue+label%3Abug)

**What happened**:

After update from 1.3.6 to 1.4.3 the web interface stops working. Portmaster detect connection and accept, but the web interface stays on connecting to portmaster.

**What did you expect to happen?**:

**How did you reproduce it?**:

Clean install portmaster and enable devolpers settings. API listening on 0.0.0.0:817.
![Screenshot from 2023-08-21 14-07-32](https://github.com/safing/portmaster-ui/assets/125558710/a1e87286-a7a4-4bf4-8cd5-26abf552cbd1)

**Debug Information**:

**Comment by OfficialEsco** [comment]
API Listen Address should be `127.0.0.1:817` no?
I can confirm the same issue with `0.0.0.0:817` but `127.0.0.1:817` works as expected

**Comment by dahkara** [comment]
Not if you want to use it on a server without GUI.
I want to connect over ip in web browser.
With the older version it works. Then new version won't load.
Or is there a change for the web UI settings?
