### ISSUE TITLE
Disable connection list reording while in use

### ISSUE THREAD

**Issue by ppacher** [safing/portmaster-ui#48]
**What would you like to be added**:

Currently the connection list in the monitoring section is reordered every few seconds. It would be great if the reordering would be paused while the list is in use (ie. the mouse is inside the list view)

**Why is this needed**:

It can be nasty if you want to click on a certain entry and the list get suddenly re-ordered.

**Comment by dhaavi** [comment]
Don't auto-close.

**Comment by northys** [comment]
Isn't this fixes already? IIRC there's a button which tells me something like "50 new connectiom press to reload". But maybe this is how it works in dev mode.

I don't recall that connections would "run away" while I'm trying to inspect something.

**Comment by dhaavi** [comment]
Yup, I think we can close this, as also the new network monitor has this considered from the beginning. Thanks!
