### ISSUE TITLE
App V.0-2-6 not working for Windows 7

### ISSUE THREAD

**Issue by Chacripan** [safing/portmaster-ui#503]
**What happened**:

Portmaster has been running flawlessly since about a year now on two Windows 7 (Home Premium, 64bit) machines.
Since the latest update (1.6.2 STABLE) however, the App-UI will not open through the regular ways any more:
**a)** tray notifier > "Open App" > no function
**b)** start menu > programs > "Portmaster" > no function
**c)** C:\Program Data\Safing\Portmaster\portmaster-start.exe > no function
"no function" = nothing happens when clicking / doubleclicking (no error message either)

**What did you expect to happen?**:

When operating steps a) to c) as described above, the App-UI should start up.

**How did you reproduce it?**:

In addition to a) to c) as described above, looking at C:\Program Data\Safing\Portmaster\updates\windows_amd64\app\ I noticed this:

**d)** \portmaster-app_v0-2-6\portmaster-app_v0-2-6.exe (latest version) > when trying to run, an error message is thrown on OS-Level (Windows Alert-Popup):
`The procedure entry point "DiscardVirtualMemory" could not be located in the dynamic link library "KERNEL32.dll". `

**e)** \portmaster-app_v0-2-5\portmaster-app_v0-2-5.exe (previous version) > App-UI does open and apparently works as normal

Also, opening the UI by browser (127.0.0.1:817/ui/modules/portmaster/dashboard) works as it should.
The core and everything else seems to be working as normal, it appears to be only a problem with the latest App-UI.

**Further Investigations**:

Apparently, Electron has dropped support for Windows 7/8 since version 23:
[Farewell, Windows 7/8/8.1](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice)

It seems that the Portmaster app has changed from Electron 20.0.3 to 27.1.2 in App version 0-2-6:
[Update electron to newest version](https://github.com/safing/portmaster-ui/commit/fc49551d9739e1628a04ed992473c4252381009b#diff-ae271b75ba16cb830a7e8e9086d2371f8b074a260d256bf81e7811d1e56510d9)

Might this explain the issue ?

**Comment by Raphty** [comment]
This is a known issue. You are correct the electron update has been responsible, we did not catch that in the Beta, which is why there was no heads up notice, we are sorry for the inconvenience.

There is a workaround:
https://wiki.safing.io/en/Portmaster/Install/Windows#windows-7-and-8 

NOTE: Since W7 has been deprecated by the developer for years at this point we strongly recommend moving away from that platform asap
