### ISSUE TITLE
Portmaster tray menu "Open App" does nothing on Windows 11 with pending Portmaster updates

### ISSUE THREAD

**Issue by Bucking-Horn** [safing/portmaster-ui#504]
**What happened**:
On a new PC that I preconfigured with Portmaster for a friend, I wanted to demonstrate Portmaster, opened the Portmaster tray menu and picked "Open App", but the UI did not start.

**What did you expect to happen?**:
The Portmaster UI should have started.

**How did you reproduce it?**:
When I came back home, I observed the same behaviour on my own PC, where it definitely had been working the evening before.

As I later found Portmaster updates to be available (see below), I guess that you have to "Open App" after pushing an update to reproduce the issue.

**Debug Information**:
I took a look at `C:\ProgramData\Safing\Portmaster\logs\start\2024-01-18-20-47-38.log`.
Portmaster is missing a component `portmaster-app.zip`: 
`
[pmstart] 2024/01/18 20:47:38 app/portmaster-app.zip failed with: could not get component: the requested file is not available locally
`

At that time, `C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app` just contained `portmaster-app_v0-2-6.zip` as well as a `.sig` and a folder matching that name.

I then took a look at a previous log file, when Portmaster was able to start and exit the UI:
```
[pmstart] 2024/01/17 20:27:50 starting C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-6\portmaster-app_v0-2-6.exe --data C:\ProgramData\Safing\Portmaster
[pmstart] 2024/01/17 20:31:19 app/portmaster-app.zip exited without error
```

Since I observed this behaviour on two PCs, I suspect the upcoming update to have messed with the file name for Portmaster's UI app to lose the version information, perhaps shortening it from `portmaster-app_v0-2-x.zip` to just `portmaster-app.zip`

**Potential workaround**:
I had no issues manually starting Portmaster UI when executing the command pried from that successful log:
`C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-6\portmaster-app_v0-2-6.exe --data C:\ProgramData\Safing\Portmaster`

Upon start, Portmaster's UI was greeting me with a message that updates were available.
After applying those updates, the "Open App" tray menu was operational again.

**Comment by Raphty** [comment]
thank you for reporting this!

I am sorry, that i missed it, I did not configure my watch settings for this repo correctly.

we are currently investigating bigger UI backend changes, that can fix this in the process.

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
