### ISSUE TITLE
Config backup, export/import

### ISSUE THREAD

**Issue by Cheyowa** [safing/portmaster-ui#505]
**What would you like to add or change?**:
A full config import/export feature. The current import/export capability is per item. Global settings are also alone in this. You can import/export global settings, but that does not include the various programs and their settings. I do NOT want to REPLACE the current functionality. I want to ADD to it.

Ideally, this should not be machine specific. So we can replicate a setup on another machine.

**Why do you and others need this?**:
For general backup

**Comment by Raphty** [comment]
this is accomplished with the upcoming sync feature which is categorized as a convenience feature and will be included in Portmaster Plus and Pro
