### ISSUE TITLE
Desktop notifications on Windows 11 Pro do not show process name

### ISSUE THREAD

**Issue by griesi007** [safing/portmaster-ui#510]
Portmaster should display process name in Desktop notifications. This is necessary if privacy mode is "Prompt" and one needs to know which process wants to connect. In the screenshot attached there is only an IPv6 address shown which is useless

![Screenshot 2024-03-09 122313](https://github.com/safing/portmaster-ui/assets/2854973/9c81cd6a-285e-4116-8222-b07619b0f1b8)

**Comment by griesi007** [comment]
@Raphty currently I am not able to provide more debug info. I think the screenshot provided is enough to show that the notification is completely useless in the shown case

**Comment by Raphty** [comment]
without debug info we cant reproduce the issue. 

this is the first time something like this came up, so it probably is to do some specification in your setup, without debug info we cant help.

further, the ip v6 you sent is 
`ff02::16	all MLDv2-capable routers`

I guess you are tweaking some things in ways that break others. 

If you want to help us make Portmaster better by contributing code, pleas let us know.

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
