### ISSUE TITLE
Simplify Dashboard

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster-ui#73]
**What would you like to be added**:

- Rename `Modules` to `Components` and `Subsystems` to `Modules`.
  - For expertise levels `Expert` and up, add technical information:
    - `Modules (</> Subsystems)`
    - `Components (</> Modules)`
  - Hide Components in expertise level `User`.
- Control Buttons:
  - Rename `System Control` to `Portmaster Controls`
  - Add Hint to `Shutdown` that only a reboot or Windows Service Restart will make Portmaster start again. Possibly use an alert for that.

**Why is this needed**:

Terminology is confusing and the UI needs to be simplified.

**Comment by davegson** [comment]
another suggestion which might confuse users:

- Active (</> Online)
- Inactive (</> Offline)

**Comment by dhaavi** [comment]
I'm okay with `Active`, but `Offline` is a bit more difficult. I would suggest this full mapping from technical to user naming: (`tech`: user)

- `Disabled`: Disabled (currently, this is not taken into account, therefore it defaults to "Offline" if disabled)
- `Dead`: Waiting (waiting for dependency to finish prepping)
- `Preparing`: Preparing
- `Offline`: Waiting (waiting for dependency to finish starting). Components stop here if disabled. 
- `Starting`: Starting
- `Online`: Active
- `Stopping`: Stopping

As you can see, Components/Modules are always prepped, no matter if they will be enabled or not. Prepping is mostly only basic startup checks.

**Comment by davegson** [comment]
I like most suggestion, the only question I'd have is when the `dead` and `offline` states come into play. Depending on the case, it might be odd to communicate those states as "waiting"

**Comment by dhaavi** [comment]
Closed by #76.

**Comment by dhaavi** [comment]
> I like most suggestions, the only question I'd have is when the `dead` and `offline` states come into play. Depending on the case, it might be odd to communicate those states as "waiting"

They would only appear as waiting when they are actually waiting on another subsystem/module (which might have a problem and stopped starting). Otherwise this state would be overridden by the "Disabled" state.
In normal operation, you would (almost) never see something waiting.
