### ISSUE TITLE
A way to block domains via 'Monitor' tab

### ISSUE THREAD

**Issue by Runnin-N-Gunnin** [safing/portmaster-ui#86]
Just tested portmaster on Win 10 - works great! Bonus points for making an actual GUI (wrapper) that is placed on taskbar instead of using a tab in a browser.

**What would you like to be added**:

A way to easily block a domain when you're looking at the overview in the 'Monitor' page.
For example, in this screenshot [here](https://camo.githubusercontent.com/27705e8d19969ba667d056f78e8f90f76ccfbe6c/68747470733a2f2f6173736574732e736166696e672e696f2f706f72746d61737465722f746f7572732f706f72746d61737465722d73637265656e73686f742d746f75722d322e706e67)

I'd like to right click a domain, for example voice.mozilla(dot)org and simply block it without having to leave the 'monitor' page.

I'm sorry if there's actually a way to do this already that I've overlooked. I'm still learning to use it properly and it's quite advanced (no complaints!) to navigate.

Thanks.

**Comment by ppacher** [comment]
Hi and thanks for contributing!

You did not overlook it because with the "old" UI it's not yet possible. I say "old" because we're doing a complete rework of the user interface which will be released at the end of the month. With the new UI we simplified at lot of stuff and also added the possibility to directly block from the monitor. So stay tuned ;)

For now, I'm going to close this issue but feel free to re-open or create a new one for whatever reason :)

**Comment by davegson** [comment]
I am re-opening this as it is a great feature request which has not yet been implemented.

We normally do not communicate deadlines, instead we only communicate our progress. Anyway, to keep you in the loop @Runnin-N-Gunnin: we are still working on the UI revamp which also includes this feature. Currently, we are testing the new UI on our local machines so the wait should not take too long anymore ;) Stay tuned, I personally am super excited for it to get out. It'll be a game changer.

Naturally, we also communicate all our progress in our [monthly update blogs](https://safing.io/blog/) and in [our newsletter](https://safing.io/#newsletter)

**Comment by dhaavi** [comment]
This has been implemented in [v0.6.0](https://github.com/safing/portmaster/releases/tag/v0.6.0). The Portmaster should notify you of the update.
