### ISSUE TITLE
UI does not support/adapt to smaller screen sizes

### ISSUE THREAD

**Issue by davegson** [safing/portmaster-ui#92]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

With a small screen, the UI cuts out the farthest right part out of the view. See:

![small_screen](https://user-images.githubusercontent.com/3080765/100752320-611e5200-33e0-11eb-8e09-d06ebc7aea6e.png)

**What you expected to happen**:

Make the left parts smaller, or at least make it scrollable so I could view the details.

**How to reproduce it (as minimally and precisely as possible)**:

Minimize the Portmaster and see it happen ;)

**Anything else we need to know?**:

**Environment**:

Portmaster Version: 0.6

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
  
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
 - Linux: `/var/lib/portmaster/logs`
 - Windows: `%PROGRAMDATA%\Portmaster\ļogs`

**Comment by Celuni** [comment]
Long domain names bug notification buttons.
![del](https://user-images.githubusercontent.com/35907275/107845837-e6f64a80-6dde-11eb-9178-40fc4ef76795.png)

**Comment by LukeSeers** [comment]
@Celuni Thanks for helping! 

I will look into fixing that issue on Monday, but I don't know when we will push the fix publicly though.

**Comment by Digital-ecologist** [comment]
Greetings and thank you for the excellent open source tool. There seems to be a related issue where the Windows accessibility setting "make everything bigger" renders parts of the PortMaster UI illegible.
This is occurring on Windows 10 professional 21H1 and Portmaster
version 0.6.14 at scale factor 150%, and 125% on a 17 inch monitor.  
![image](https://user-images.githubusercontent.com/42946430/119837532-ad9aa400-bed0-11eb-8302-894cffe49036.png)
![image](https://user-images.githubusercontent.com/42946430/119837659-cd31cc80-bed0-11eb-9540-f72e5da1d30b.png) 
Unfortunately, with my vision, the 100% setting that works with PortMaster makes everything else on my screen too small. My current workaround is decreasing the zoom scale factor whenever I'm interacting with the PortMaster UI, but if it's possible to resolve the underlying issue, that would be greatly appreciated. Thank you for your hard work

**Comment by LukeSeers** [comment]
@Digital-ecologist Hey mate. Thanks for the feedback and I can assure you that we are working on this. We've been slowly making the Portmaster UI "compact-able" and I think when we release this, you should start to see improvements. 

I would be very grateful if your able to send us some more feedback when we release the "compact-able" update.  I would like to add that it wont be one huge update, it will be added a bit at a time.

**Comment by Digital-ecologist** [comment]
Thanks for considering accessibility. I'm not sure if this is helpful to know, but it does seem to be Windows specific. The UI look spectacular out-of-the-box on my Linux Mint 20.1 XFCE system. That said, I handle visual accessibility on that system completely differently. I don't use the fractional scaling at all, and just use the plasticity of XFCE  to make the system fonts, and UI elements comfortable sizes.  I'll try to keep you posted accessibility wise as the project evolves. Thanks again.

**Comment by dhaavi** [comment]
> I'll try to keep you posted accessibility wise as the project evolves.

That would be amazing! Thanks!
