### ISSUE TITLE
UI no longer shows Version/Licence and its details

### ISSUE THREAD

**Issue by davegson** [safing/portmaster-ui#93]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

Reported from a user via support. Pretty self explanatory from the title, here's a screenshot:

![Screen Shot 2020-12-02 at 12 30 37 PM](https://user-images.githubusercontent.com/3080765/100868410-7b653800-3493-11eb-95f5-72b1e0a8b682.png)

**What you expected to happen**:

Show the version number etc.

**How to reproduce it (as minimally and precisely as possible)**:

Go to settings 🙃

**Anything else we need to know?**:

Maybe it's environment specific, but was the same on my Portmaster too.

**Environment**:

Portmaster Version: 

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
  
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
 - Linux: `/var/lib/portmaster/logs`
 - Windows: `%PROGRAMDATA%\Portmaster\ļogs`

**Comment by ppacher** [comment]
@davegson Can you please attach the logs the next time this happens? We've seen this once on @dhaavi machine but wasn't able to reproduce it.

**Comment by davegson** [comment]
true, when loading it again was there again - odd... I just assumed this was a default since the support ticket also reported this. Will do and also ask the person to send logs in case it persists on their side
