### ISSUE TITLE
Text missing from UI

### ISSUE THREAD

**Issue by wahlis** [safing/portmaster-ui#95]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:
Text is missing from interface

![{0E51EE29-6018-45AC-B544-6A8DCCF33E46}](https://user-images.githubusercontent.com/1257241/101874698-4aff5700-3b81-11eb-8ba8-f0c7b0902415.png)
![{729022C6-7D28-486A-9AB4-12475889C884}](https://user-images.githubusercontent.com/1257241/101874704-4dfa4780-3b81-11eb-8d83-84ef1184c0b7.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I've tried installing on two different Windows 10 machines with the same issue on both. The common between them is that they use Swedish in the Win UI.

**Environment**:

Portmaster Version: 
0.6.2

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
  
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
 - Linux: `/var/lib/portmaster/logs`
 - Windows: `%PROGRAMDATA%\Portmaster\ļogs`

**Comment by ppacher** [comment]
Hi @wahlis , thanks for report this issue.

From what I see I suspect that the actual issue is not within UI (as it can display at least some text) but rather in the portmaster system service that generates the "profile" names. Can you confirm that the settings page (cog-icon on the bottom-left) works while the overview in the app-settings page does not (the second menu point)?

**Comment by dhaavi** [comment]
I wonder if there are language differences here. Could you run this snippet in a PowerShell (paste + enter) and post the result here?
`Get-ItemProperty C:\Windows\System32\svchost.exe | Format-List`

I will make the function more resilient so that it correctly falls back to an alternative value.

**Comment by wahlis** [comment]
Yes, I can confirm that it works fine in latest release. Thanks!
